DROP FUNCTION find_service_road_location_for_centerline_crash;

DROP FUNCTION find_noncr3_collisions_for_location;

DROP FUNCTION find_cr3_collisions_for_location;

DROP FUNCTION search_atd_location_crashes;

DROP FUNCTION search_atd_crash_locations;

DROP FUNCTION search_atd_crash_location;
