import re
from .helpers_import_filters import *

CRIS_TXDOT_FIELDS = {
    "crash": {
        "query_name": "insertCrashQuery",
        "function_name": "insert_atd_txdot_crashes",
        "filters": [
            [
                filter_numeric_field,
                [
                    "crash_id",
                    "rpt_cris_cnty_id",
                    "rpt_city_id",
                    "rpt_latitude",
                    "rpt_longitude",
                    "rpt_rdwy_sys_id",
                    "rpt_road_part_id",
                    "crash_speed_limit",
                    "rpt_sec_rdwy_sys_id",
                    "rpt_sec_road_part_id",
                    "rpt_ref_mark_offset_amt",
                    "wthr_cond_id",
                    "light_cond_id",
                    "entr_road_id",
                    "road_type_id",
                    "road_algn_id",
                    "surf_cond_id",
                    "traffic_cntl_id",
                    "investigat_agency_id",
                    "investigat_area_id",
                    "investigat_district_id",
                    "investigat_region_id",
                    "bridge_detail_id",
                    "harm_evnt_id",
                    "intrsct_relat_id",
                    "fhe_collsn_id",
                    "obj_struck_id",
                    "othr_factr_id",
                    "road_part_adj_id",
                    "road_cls_id",
                    "road_relat_id",
                    "phys_featr_1_id",
                    "phys_featr_2_id",
                    "cnty_id",
                    "city_id",
                    "latitude",
                    "longitude",
                    "dfo",
                    "control",
                    "section",
                    "milepoint",
                    "ref_mark_nbr",
                    "ref_mark_displ",
                    "control_2",
                    "section_2",
                    "milepoint_2",
                    "crash_sev_id",
                    "pop_group_id",
                    "curb_type_left_id",
                    "curb_type_right_id",
                    "shldr_type_left_id",
                    "shldr_width_left",
                    "shldr_use_left_id",
                    "shldr_type_right_id",
                    "shldr_width_right",
                    "shldr_use_right_id",
                    "median_type_id",
                    "median_width",
                    "rural_urban_type_id",
                    "func_sys_id",
                    "adt_curnt_amt",
                    "adt_curnt_year",
                    "adt_adj_curnt_amt",
                    "pct_single_trk_adt",
                    "pct_combo_trk_adt",
                    "trk_aadt_pct",
                    "curve_type_id",
                    "curve_lngth",
                    "cd_degr",
                    "delta_left_right_id",
                    "dd_degr",
                    "sus_serious_injry_cnt",
                    "nonincap_injry_cnt",
                    "poss_injry_cnt",
                    "non_injry_cnt",
                    "unkn_injry_cnt",
                    "tot_injry_cnt",
                    "death_cnt",
                    "mpo_id",
                    "investigat_service_id",
                    "investigat_da_id",
                    "latitude_geocoded",
                    "longitude_geocoded",
                    "latitude_primary",
                    "longitude_primary",
                    "geocode_provider",
                    "qa_status",
                    "est_comp_cost",
                    "est_econ_cost",
                    "apd_confirmed_death_count",
                    "speed_mgmt_points",
                ]
            ]
        ]
    },

    "charges": {
        "query_name": "insertChargeQuery",
        "function_name": "insert_atd_txdot_charges",
        "filters": [
            [filter_numeric_empty_to_zero, ["charge_cat_id"]],
            [filter_numeric_null_to_zero, ["charge_cat_id"]],
            [filter_numeric_field, ["charge_id", "crash_id", "unit_nbr", "prsn_nbr", "charge_cat_id"]],
            [filter_text_null_to_empty, ["citation_nbr"]]
        ]
    },

    "unit": {
        "query_name": "insertUnitQuery",
        "function_name": "insert_atd_txdot_units",
        "filters": [
            [
                filter_remove_field,
                [
                    # PII Fields that need to be removed
                    "ownr_last_name",
                    "ownr_first_name",
                    "ownr_street_nbr",
                    "ownr_street_pfx",
                    "ownr_street_name",
                    "ownr_street_sfx",
                    "ownr_apt_nbr",
                    # These fields are not present in the database
                    "trlr_gvwr",
                    "trlr_rgvw",
                    "trlr_type_id",
                    "trlr_disabling_dmag_id",
                    "cmv_intermodal_container_permit_fl",
                    "cmv_actual_gross_weight"
                ]
            ],
            [
                filter_numeric_field,
                [
                    "crash_id",
                    "unit_nbr",
                    "unit_desc_id",
                    "veh_lic_state_id",
                    "veh_mod_year",
                    "veh_color_id",
                    "veh_make_id",
                    "veh_mod_id",
                    "veh_body_styl_id",
                    "ownr_state_id",
                    "fin_resp_proof_id",
                    "fin_resp_type_id",
                    "veh_dmag_area_1_id",
                    "veh_dmag_scl_1_id",
                    "force_dir_1_id",
                    "veh_dmag_area_2_id",
                    "veh_dmag_scl_2_id",
                    "force_dir_2_id",
                    "cmv_veh_oper_id",
                    "cmv_carrier_id_type_id",
                    "cmv_carrier_state_id",
                    "cmv_road_acc_id",
                    "cmv_veh_type_id",
                    "hazmat_cls_1_id",
                    "hazmat_idnbr_1_id",
                    "hazmat_cls_2_id",
                    "hazmat_idnbr_2_id",
                    "cmv_cargo_body_id",
                    "trlr1_type_id",
                    "trlr2_type_id",
                    "cmv_evnt1_id",
                    "cmv_evnt2_id",
                    "cmv_evnt3_id",
                    "cmv_evnt4_id",
                    "contrib_factr_1_id",
                    "contrib_factr_2_id",
                    "contrib_factr_3_id",
                    "contrib_factr_p1_id",
                    "contrib_factr_p2_id",
                    "veh_dfct_1_id",
                    "veh_dfct_2_id",
                    "veh_dfct_3_id",
                    "veh_dfct_p1_id",
                    "veh_dfct_p2_id",
                    "veh_trvl_dir_id",
                    "first_harm_evt_inv_id",
                    "cmv_trlr1_disabling_dmag_id",
                    "cmv_trlr2_disabling_dmag_id",
                    "cmv_bus_type_id",
                    "unit_id"
                ]
            ],
        ]
    },

    "person": {
        "query_name": "insertPersonQuery",
        "function_name": "insert_atd_txdot_person",
        "filters": [
            [
                filter_remove_field,
                [
                    # PII Fields that need to be removed
                    "prsn_last_name",
                    "prsn_first_name",
                    "prsn_mid_name",
                    "prsn_name_sfx",
                ]
            ],
            [
                filter_numeric_field,
                [
                    "crash_id",
                    "unit_nbr",
                    "prsn_nbr",
                    "prsn_type_id",
                    "prsn_occpnt_pos_id",
                    "prsn_injry_sev_id",
                    "prsn_age",
                    "prsn_ethnicity_id",
                    "prsn_gndr_id",
                    "prsn_ejct_id",
                    "prsn_rest_id",
                    "prsn_airbag_id",
                    "prsn_helmet_id",
                    "prsn_alc_spec_type_id",
                    "prsn_alc_rslt_id",
                    "prsn_drg_spec_type_id",
                    "prsn_drg_rslt_id",
                    "sus_serious_injry_cnt",
                    "nonincap_injry_cnt",
                    "poss_injry_cnt",
                    "non_injry_cnt",
                    "unkn_injry_cnt",
                    "tot_injry_cnt",
                    "death_cnt",
                    "person_id",
                    "years_of_life_lost",
                ]
            ],
        ]
    },

    "primaryperson": {
        "query_name": "insertPersonQuery",
        "function_name": "insert_atd_txdot_primaryperson",
        "filters": [
            [
                filter_remove_field,
                [
                    # PII Fields that need to be removed
                    "prsn_last_name",
                    "prsn_first_name",
                    "prsn_mid_name",
                    "prsn_name_sfx",
                    "drvr_lic_state_id",
                    "drvr_lic_number",
                    "drvr_dob",
                    "drvr_street_nbr",
                    "drvr_street_pfx",
                    "drvr_street_name",
                    "drvr_street_sfx",
                    "drvr_apt_nbr",
                ]
            ],
            [
                filter_numeric_field,
                [
                    "crash_id",
                    "unit_nbr",
                    "prsn_nbr",
                    "prsn_type_id",
                    "prsn_occpnt_pos_id",
                    "prsn_injry_sev_id",
                    "prsn_age",
                    "prsn_ethnicity_id",
                    "prsn_gndr_id",
                    "prsn_ejct_id",
                    "prsn_rest_id",
                    "prsn_airbag_id",
                    "prsn_helmet_id",
                    "prsn_alc_spec_type_id",
                    "prsn_alc_rslt_id",
                    "prsn_drg_spec_type_id",
                    "prsn_drg_rslt_id",
                    "drvr_drg_cat_1_id",
                    "sus_serious_injry_cnt",
                    "nonincap_injry_cnt",
                    "poss_injry_cnt",
                    "non_injry_cnt",
                    "unkn_injry_cnt",
                    "tot_injry_cnt",
                    "death_cnt",
                    "drvr_lic_type_id",
                    "drvr_lic_cls_id",
                    "drvr_state_id",
                    "primaryperson_id",
                    "years_of_life_lost",
                ]
            ],
        ]
    }
}