import re
from .helpers_import_filters import *

CRIS_TXDOT_FIELDS = {
    "crash": {
        "query_name": "insertCrashQuery",
        "function_name": "insert_atd_txdot_crashes",
        "filters": [
            [filter_remove_field, []],
            [
                filter_numeric_field,
                [
                    "crash_id",
                    "rpt_cris_cnty_id",
                    "rpt_city_id",
                    "rpt_latitude",
                    "rpt_longitude",
                    "rpt_rdwy_sys_id",
                    "rpt_road_part_id",
                    "crash_speed_limit",
                    "rpt_sec_rdwy_sys_id",
                    "rpt_sec_road_part_id",
                    "rpt_ref_mark_offset_amt",
                    "wthr_cond_id",
                    "light_cond_id",
                    "entr_road_id",
                    "road_type_id",
                    "road_algn_id",
                    "surf_cond_id",
                    "traffic_cntl_id",
                    "investigat_agency_id",
                    "investigat_area_id",
                    "investigat_district_id",
                    "investigat_region_id",
                    "bridge_detail_id",
                    "harm_evnt_id",
                    "intrsct_relat_id",
                    "fhe_collsn_id",
                    "obj_struck_id",
                    "othr_factr_id",
                    "road_part_adj_id",
                    "road_cls_id",
                    "road_relat_id",
                    "phys_featr_1_id",
                    "phys_featr_2_id",
                    "cnty_id",
                    "city_id",
                    "latitude",
                    "longitude",
                    "dfo",
                    "control",
                    "section",
                    "milepoint",
                    "ref_mark_nbr",
                    "ref_mark_displ",
                    "control_2",
                    "section_2",
                    "milepoint_2",
                    "crash_sev_id",
                    "pop_group_id",
                    "curb_type_left_id",
                    "curb_type_right_id",
                    "shldr_type_left_id",
                    "shldr_width_left",
                    "shldr_use_left_id",
                    "shldr_type_right_id",
                    "shldr_width_right",
                    "shldr_use_right_id",
                    "median_type_id",
                    "median_width",
                    "rural_urban_type_id",
                    "func_sys_id",
                    "adt_curnt_amt",
                    "adt_curnt_year",
                    "adt_adj_curnt_amt",
                    "pct_single_trk_adt",
                    "pct_combo_trk_adt",
                    "trk_aadt_pct",
                    "curve_type_id",
                    "curve_lngth",
                    "cd_degr",
                    "delta_left_right_id",
                    "dd_degr",
                    "sus_serious_injry_cnt",
                    "nonincap_injry_cnt",
                    "poss_injry_cnt",
                    "non_injry_cnt",
                    "unkn_injry_cnt",
                    "tot_injry_cnt",
                    "death_cnt",
                    "mpo_id",
                    "investigat_service_id",
                    "investigat_da_id",
                    "latitude_geocoded",
                    "longitude_geocoded",
                    "latitude_primary",
                    "longitude_primary",
                    "geocode_provider",
                    "qa_status",
                    "est_comp_cost",
                    "est_econ_cost",
                    "apd_confirmed_death_count",
                    "speed_mgmt_points",
                ],
            ],
        ],
    },
    "charges": {
        "query_name": "insertChargeQuery",
        "function_name": "insert_atd_txdot_charges",
        "filters": [
            [filter_numeric_empty_to_zero, ["charge_cat_id"]],
            [filter_numeric_null_to_zero, ["charge_cat_id"]],
            [
                filter_numeric_field,
                ["charge_id", "crash_id", "unit_nbr", "prsn_nbr", "charge_cat_id"],
            ],
            [filter_text_null_to_empty, ["citation_nbr"]],
        ],
    },
    "unit": {
        "query_name": "insertUnitQuery",
        "function_name": "insert_atd_txdot_units",
        "filters": [
            [
                filter_remove_field,
                [
                    # PII Fields that need to be removed
                    "ownr_last_name",
                    "ownr_first_name",
                    "ownr_street_nbr",
                    "ownr_street_pfx",
                    "ownr_street_name",
                    "ownr_street_sfx",
                    "ownr_apt_nbr",
                    # These fields are not present in the database
                    "trlr_gvwr",
                    "trlr_rgvw",
                    "trlr_type_id",
                    "trlr_disabling_dmag_id",
                    "cmv_intermodal_container_permit_fl",
                    "cmv_actual_gross_weight",
                ],
            ],
            [
                filter_numeric_field,
                [
                    "crash_id",
                    "unit_nbr",
                    "unit_desc_id",
                    "veh_lic_state_id",
                    "veh_mod_year",
                    "veh_color_id",
                    "veh_make_id",
                    "veh_mod_id",
                    "veh_body_styl_id",
                    "ownr_state_id",
                    "fin_resp_proof_id",
                    "fin_resp_type_id",
                    "cmv_veh_oper_id",
                    "cmv_carrier_id_type_id",
                    "cmv_carrier_state_id",
                    "cmv_road_acc_id",
                    "cmv_veh_type_id",
                    "hazmat_cls_1_id",
                    "hazmat_idnbr_1_id",
                    "hazmat_cls_2_id",
                    "hazmat_idnbr_2_id",
                    "cmv_cargo_body_id",
                    "trlr1_type_id",
                    "trlr2_type_id",
                    "cmv_evnt1_id",
                    "cmv_evnt2_id",
                    "cmv_evnt3_id",
                    "cmv_evnt4_id",
                    "contrib_factr_1_id",
                    "contrib_factr_2_id",
                    "contrib_factr_3_id",
                    "contrib_factr_p1_id",
                    "contrib_factr_p2_id",
                    "veh_dfct_1_id",
                    "veh_dfct_2_id",
                    "veh_dfct_3_id",
                    "veh_dfct_p1_id",
                    "veh_dfct_p2_id",
                    "veh_trvl_dir_id",
                    "first_harm_evt_inv_id",
                    "sus_serious_injry_cnt",
                    "nonincap_injry_cnt",
                    "poss_injry_cnt",
                    "non_injry_cnt",
                    "unkn_injry_cnt",
                    "tot_injry_cnt",
                    "death_cnt",
                    "cmv_trlr1_disabling_dmag_id",
                    "cmv_trlr2_disabling_dmag_id",
                    "cmv_bus_type_id",
                    "unit_id",
                    "veh_damage_description1_id",
                    "veh_damage_severity1_id",
                    "veh_damage_direction_of_force1_id",
                    "veh_damage_description2_id",
                    "veh_damage_severity2_id",
                    "veh_damage_direction_of_force2_id",
                    "pedestrian_action_id",
                    "pedalcyclist_action_id",
                    "pbcat_pedestrian_id",
                    "pbcat_pedalcyclist_id",
                    "e_scooter_id",
                    "autonomous_unit_id",
                ],
            ],
            [
                filter_numeric_empty_to_null,
                [
                    "cmv_bus_type_id",
                    "pedestrian_action_id",
                    "pedalcyclist_action_id",
                    "pbcat_pedestrian_id",
                    "pbcat_pedalcyclist_id",
                    "e_scooter_id",
                    "autonomous_unit_id",
                ],
            ],
        ],
    },
    "person": {
        "query_name": "insertPersonQuery",
        "function_name": "insert_atd_txdot_person",
        "filters": [
            [
                filter_remove_field,
                [
                    # PII Fields that need to be removed
                    "prsn_last_name",
                    "prsn_first_name",
                    "prsn_mid_name",
                    "prsn_name_sfx",
                ],
            ],
            [
                filter_numeric_field,
                [
                    "crash_id",
                    "unit_nbr",
                    "prsn_nbr",
                    "prsn_type_id",
                    "prsn_occpnt_pos_id",
                    "prsn_injry_sev_id",
                    "prsn_age",
                    "prsn_ethnicity_id",
                    "prsn_gndr_id",
                    "prsn_ejct_id",
                    "prsn_rest_id",
                    "prsn_airbag_id",
                    "prsn_helmet_id",
                    "prsn_alc_spec_type_id",
                    "prsn_alc_rslt_id",
                    "prsn_drg_spec_type_id",
                    "prsn_drg_rslt_id",
                    "sus_serious_injry_cnt",
                    "nonincap_injry_cnt",
                    "poss_injry_cnt",
                    "non_injry_cnt",
                    "unkn_injry_cnt",
                    "tot_injry_cnt",
                    "death_cnt",
                    "person_id",
                    "years_of_life_lost",
                ],
            ],
        ],
    },
    "primaryperson": {
        "query_name": "insertPersonQuery",
        "function_name": "insert_atd_txdot_primaryperson",
        "filters": [
            [
                filter_remove_field,
                [
                    # PII Fields that need to be removed
                    "prsn_last_name",
                    "prsn_first_name",
                    "prsn_mid_name",
                    "prsn_name_sfx",
                    "drvr_lic_state_id",
                    "drvr_lic_number",
                    "drvr_dob",
                    "drvr_street_nbr",
                    "drvr_street_pfx",
                    "drvr_street_name",
                    "drvr_street_sfx",
                    "drvr_apt_nbr",
                ],
            ],
            [
                filter_numeric_field,
                [
                    "crash_id",
                    "unit_nbr",
                    "prsn_nbr",
                    "prsn_type_id",
                    "prsn_occpnt_pos_id",
                    "prsn_injry_sev_id",
                    "prsn_age",
                    "prsn_ethnicity_id",
                    "prsn_gndr_id",
                    "prsn_ejct_id",
                    "prsn_rest_id",
                    "prsn_airbag_id",
                    "prsn_helmet_id",
                    "prsn_alc_spec_type_id",
                    "prsn_alc_rslt_id",
                    "prsn_drg_spec_type_id",
                    "prsn_drg_rslt_id",
                    "drvr_drg_cat_1_id",
                    "sus_serious_injry_cnt",
                    "nonincap_injry_cnt",
                    "poss_injry_cnt",
                    "non_injry_cnt",
                    "unkn_injry_cnt",
                    "tot_injry_cnt",
                    "death_cnt",
                    "drvr_lic_type_id",
                    "drvr_lic_cls_id",
                    "drvr_state_id",
                    "primaryperson_id",
                    "years_of_life_lost",
                ],
            ],
        ],
    },
}

CRIS_TXDOT_COMPARE_FIELDS_LIST = [
    "crash_fatal_fl",
    "private_dr_fl",
    "rpt_outside_city_limit_fl",
    "crash_date",
    "crash_time",
    "case_id",
    "rpt_latitude",
    "rpt_longitude",
    "rpt_hwy_num",
    "rpt_block_num",
    "rpt_street_name",
    "rpt_sec_hwy_num",
    "rpt_sec_block_num",
    "rpt_sec_street_name",
    "hwy_nbr",
    "hwy_sys",
    "hwy_sys_2",
    "hwy_nbr_2",
    "city_id",
    "latitude",
    "longitude",
    "street_name",
    "street_nbr",
    "street_name_2",
    "street_nbr_2",
    "sus_serious_injry_cnt",
    "nonincap_injry_cnt",
    "poss_injry_cnt",
    "non_injry_cnt",
    "unkn_injry_cnt",
    "tot_injry_cnt",
    "death_cnt",
]


CRIS_TXDOT_COMPARE_FIELD_TYPE = {
    "crash_id": "int",
    "crash_fatal_fl": "string",
    "cmv_involv_fl": "string",
    "schl_bus_fl": "string",
    "rr_relat_fl": "string",
    "medical_advisory_fl": "string",
    "amend_supp_fl": "string",
    "active_school_zone_fl": "string",
    "crash_date": "date",
    "crash_time": "time",
    "case_id": "string",
    "local_use": "string",
    "rpt_cris_cnty_id": "int",
    "rpt_city_id": "int",
    "rpt_outside_city_limit_fl": "string",
    "thousand_damage_fl": "string",
    "rpt_latitude": "decimal",
    "rpt_longitude": "decimal",
    "rpt_rdwy_sys_id": "int",
    "rpt_hwy_num": "string",
    "rpt_hwy_sfx": "string",
    "rpt_road_part_id": "int",
    "rpt_block_num": "string",
    "rpt_street_pfx": "string",
    "rpt_street_name": "string",
    "rpt_street_sfx": "string",
    "private_dr_fl": "string",
    "toll_road_fl": "string",
    "crash_speed_limit": "int",
    "road_constr_zone_fl": "string",
    "road_constr_zone_wrkr_fl": "string",
    "rpt_street_desc": "string",
    "at_intrsct_fl": "string",
    "rpt_sec_rdwy_sys_id": "int",
    "rpt_sec_hwy_num": "string",
    "rpt_sec_hwy_sfx": "string",
    "rpt_sec_road_part_id": "int",
    "rpt_sec_block_num": "string",
    "rpt_sec_street_pfx": "string",
    "rpt_sec_street_name": "string",
    "rpt_sec_street_sfx": "string",
    "rpt_ref_mark_offset_amt": "decimal",
    "rpt_ref_mark_dist_uom": "string",
    "rpt_ref_mark_dir": "string",
    "rpt_ref_mark_nbr": "string",
    "rpt_sec_street_desc": "string",
    "rpt_crossingnumber": "string",
    "wthr_cond_id": "int",
    "light_cond_id": "int",
    "entr_road_id": "int",
    "road_type_id": "int",
    "road_algn_id": "int",
    "surf_cond_id": "int",
    "traffic_cntl_id": "int",
    "investigat_notify_time": "time",
    "investigat_notify_meth": "string",
    "investigat_arrv_time": "time",
    "report_date": "date",
    "investigat_comp_fl": "string",
    "investigator_name": "string",
    "id_number": "string",
    "ori_number": "string",
    "investigat_agency_id": "int",
    "investigat_area_id": "int",
    "investigat_district_id": "int",
    "investigat_region_id": "int",
    "bridge_detail_id": "int",
    "harm_evnt_id": "int",
    "intrsct_relat_id": "int",
    "fhe_collsn_id": "int",
    "obj_struck_id": "int",
    "othr_factr_id": "int",
    "road_part_adj_id": "int",
    "road_cls_id": "int",
    "road_relat_id": "int",
    "phys_featr_1_id": "int",
    "phys_featr_2_id": "int",
    "cnty_id": "int",
    "city_id": "int",
    "latitude": "decimal",
    "longitude": "decimal",
    "hwy_sys": "string",
    "hwy_nbr": "string",
    "hwy_sfx": "string",
    "dfo": "decimal",
    "street_name": "string",
    "street_nbr": "string",
    "control": "int",
    "section": "int",
    "milepoint": "decimal",
    "ref_mark_nbr": "int",
    "ref_mark_displ": "decimal",
    "hwy_sys_2": "string",
    "hwy_nbr_2": "string",
    "hwy_sfx_2": "string",
    "street_name_2": "string",
    "street_nbr_2": "string",
    "control_2": "int",
    "section_2": "int",
    "milepoint_2": "decimal",
    "txdot_rptable_fl": "string",
    "onsys_fl": "string",
    "rural_fl": "string",
    "crash_sev_id": "int",
    "pop_group_id": "int",
    "located_fl": "string",
    "day_of_week": "string",
    "hwy_dsgn_lane_id": "string",
    "hwy_dsgn_hrt_id": "string",
    "hp_shldr_left": "string",
    "hp_shldr_right": "string",
    "hp_median_width": "string",
    "base_type_id": "string",
    "nbr_of_lane": "string",
    "row_width_usual": "string",
    "roadbed_width": "string",
    "surf_width": "string",
    "surf_type_id": "string",
    "curb_type_left_id": "int",
    "curb_type_right_id": "int",
    "shldr_type_left_id": "int",
    "shldr_width_left": "int",
    "shldr_use_left_id": "int",
    "shldr_type_right_id": "int",
    "shldr_width_right": "int",
    "shldr_use_right_id": "int",
    "median_type_id": "int",
    "median_width": "int",
    "rural_urban_type_id": "int",
    "func_sys_id": "int",
    "adt_curnt_amt": "int",
    "adt_curnt_year": "int",
    "adt_adj_curnt_amt": "int",
    "pct_single_trk_adt": "decimal",
    "pct_combo_trk_adt": "decimal",
    "trk_aadt_pct": "decimal",
    "curve_type_id": "int",
    "curve_lngth": "int",
    "cd_degr": "int",
    "delta_left_right_id": "int",
    "dd_degr": "int",
    "feature_crossed": "string",
    "structure_number": "string",
    "i_r_min_vert_clear": "string",
    "approach_width": "string",
    "bridge_median_id": "string",
    "bridge_loading_type_id": "string",
    "bridge_loading_in_1000_lbs": "string",
    "bridge_srvc_type_on_id": "string",
    "bridge_srvc_type_under_id": "string",
    "culvert_type_id": "string",
    "roadway_width": "string",
    "deck_width": "string",
    "bridge_dir_of_traffic_id": "string",
    "bridge_rte_struct_func_id": "string",
    "bridge_ir_struct_func_id": "string",
    "crossingnumber": "string",
    "rrco": "string",
    "poscrossing_id": "string",
    "wdcode_id": "string",
    "standstop": "string",
    "yield": "string",
    "sus_serious_injry_cnt": "int",
    "nonincap_injry_cnt": "int",
    "poss_injry_cnt": "int",
    "non_injry_cnt": "int",
    "unkn_injry_cnt": "int",
    "tot_injry_cnt": "int",
    "death_cnt": "int",
    "mpo_id": "int",
    "investigat_service_id": "int",
    "investigat_da_id": "int",
    "investigator_narrative": "string",
}
