services:
  graphql-engine:
    image: hasura/graphql-engine:v2.43.0
    volumes:
      - ./viewer/graphql-engine-metadata:/metadata
    container_name: visionzero-graphql-engine
    ports:
      - 8084:8080
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://visionzero:visionzero@postgis:5432/atd_vz_data
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets

  postgis:
    image: frankinaustin/postgis-multiarch:14-3.3
    environment:
      POSTGRES_PASSWORD: "visionzero"
      POSTGRES_USER: "visionzero"
      POSTGRES_DB: "atd_vz_data"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  schemaspy:
    image: schemaspy/schemaspy:latest
    volumes:
      # - ./database/schemaspy_docs/:/output/
      - ./database/schema_spy.cfg:/schemaspy.properties
