# ems__incidents.mvc_form_position_in_vehicle mapped to lookups.occpnt_pos.label
# values with no match are excluded from this list
EMS_POS_IN_VEHICLE_TO_CRIS_OCC_POS_MAP = {
    "front seat - left side (or motorcycle driver)": "front left or motorcycle driver",
    "front seat - middle": "front center or motorcycle sidecar passenger",
    "front seat - right side": "front right",
    "second seat - left side (or motorcycle passenger)": "second seat left or motorcycle back passenger",
    "second seat - middle": "second seat center",
    "second seat - right side": "second seat right",
    "third row - left side (or motorcycle passenger)": "third seat left",
    "third row - middle": "third seat center",
    "third row - right side": "third seat right",
}


# lookups.mode_category.label to ems__incident.travel_mode mapped
CRIS_MODE_CAT_TO_EMS_TRAVEL_MODE_MAP = {
    "bicycle": "bicycle",
    "pedestrian": "pedestrian",
    "e-scooter": "e-scooter",
    "micromobility device": "e-scooter",
    "passenger car": "motor vehicle",
    "large passenger vehicle": "motor vehicle",
    "motor vehicle – other": "motor vehicle",
    "motorcycle": "motorcycle",
    "other/unknown": None,
    "train": None,
}

"""
The EMS `pcr_transport_destination` field is a controlled domain
 of ~30 values. The CRIS `prsn_taken_to` field is a free text
 field with thousands of values. The below map was created by
 reviewing our manually matched ems-person records and identifying
 valid matching values. This covers ~97% of transport destination
 from EMS records that were manually matched.

 Note that all values have been lower-cased.
"""
CRIS_TO_EMS_TRANSPORT_DEST = {
    "south austin hopital": "south austin medical center",
    "south austin hospital": "south austin medical center",
    "south austin medical center": "south austin medical center",
    "st david - south austin hospital": "south austin medical center",
    "st david south austin": "south austin medical center",
    "st david south hospital": "south austin medical center",
    "st david's s. austin hos: w. ben white": "south austin medical center",
    "st david's s. austin hospital": "south austin medical center",
    "st david's south austin": "south austin medical center",
    "st david's south austin medical center": "south austin medical center",
    "st davids south austin": "south austin medical center",
    "st. david south austin": "south austin medical center",
    "st. david's hospital south austin": "south austin medical center",
    "st. david's south austin medical center": "south austin medical center",
    "st. davids medical center": "south austin medical center",
    "st. davids south austin": "south austin medical center",
    "dell seton medical center": "dell seton medical center at ut",
    "dell seton": "dell seton medical center at ut",
    "umc at brackenridge": "dell seton medical center at ut",
    "dell ston at ut": "dell seton medical center at ut",
    "del seton": "dell seton medical center at ut",
    "dell seton at ut": "dell seton medical center at ut",
    "acension dell seton medical center": "dell seton medical center at ut",
    "dell seton 1500": "dell seton medical center at ut",
    "dell seaton": "dell seton medical center at ut",
    "dell seton hospital": "dell seton medical center at ut",
    "dell seton med center @ ut": "dell seton medical center at ut",
    "dell seton med center at ut": "dell seton medical center at ut",
    "ut dell seton medical center": "dell seton medical center at ut",
    "dell-seton": "dell seton medical center at ut",
    "dell seton main": "dell seton medical center at ut",
    "del seton medical center": "dell seton medical center at ut",
    "dell seton med ctr": "dell seton medical center at ut",
    "dell seton 1500 red river st": "dell seton medical center at ut",
    "dell seton mcut": "dell seton medical center at ut",
    "dell seton medical center at ut": "dell seton medical center at ut",
    "dell senton medical center": "dell seton medical center at ut",
    "dell medical center": "dell seton medical center at ut",
    "dell seaton main": "dell seton medical center at ut",
    "dell seton mc": "dell seton medical center at ut",
    "ut dell seton medical cetner": "dell seton medical center at ut",
    "del-seton medical center": "dell seton medical center at ut",
    "dell-seton medical center": "dell seton medical center at ut",
    "dell seton medical center, austin": "dell seton medical center at ut",
    "dell seton mcut er": "dell seton medical center at ut",
    "dell-seton hospital": "dell seton medical center at ut",
    "ascension dell-seton mcut": "dell seton medical center at ut",
    "dell center main": "dell seton medical center at ut",
    "dell seton ascension": "dell seton medical center at ut",
    "dell seton medical center ut": "dell seton medical center at ut",
    "dell seton 1500 red river": "dell seton medical center at ut",
    "dellseton": "dell seton medical center at ut",
    "dell seton @ut": "dell seton medical center at ut",
    "dell seaton medical center": "dell seton medical center at ut",
    "round rock medical center": "saint david's round rock medical center",
    "st david's round rock med ctr": "saint david's round rock medical center",
    "st davids medical center round rock": "saint david's round rock medical center",
    "st. davids round rock medical center": "saint david's round rock medical center",
    "st. david's round rock medical center": "saint david's round rock medical center",
    "st.davids round rock": "saint david's round rock medical center",
    "st davids round rock": "saint david's round rock medical center",
    "round rock hospital": "saint david's round rock medical center",
    "saint david round rock": "saint david's round rock medical center",
    "st. david's round rock er": "saint david's round rock medical center",
    "st. davids medical center round rock": "saint david's round rock medical center",
    "st david's round rock": "saint david's round rock medical center",
    "st. david round rock medical": "saint david's round rock medical center",
    "round rock": "saint david's round rock medical center",
    "north austin medical center": "north austin medical center",
    "st davids north austin": "north austin medical center",
    "st davids north": "north austin medical center",
    "st david's n. austin med ctr: n. mopac": "north austin medical center",
    "st davids north medical center": "north austin medical center",
    "st david's north": "north austin medical center",
    "st. davids medical center": "saint david's medical center",
    "st david's med ctr": "saint david's medical center",
    "st. david's medical center": "saint david's medical center",
    "st david's s. austin hospital": "saint david's medical center",
    "dell childrens medical center": "dell children's medical center",
    "dell children's medical center": "dell children's medical center",
    "dell childrens hospital": "dell children's medical center",
    "dell childrens": "dell children's medical center",
    "seton medical center austin": "seton medical center austin",
    "seton med ctr": "seton medical center austin",
    "seton northwest": "seton northwest hospital",
    "seteon nw": "seton northwest hospital",
    "seton medical center hays": "seton medical center hays",
    "baylor, scott and white": "baylor scott and white - austin",
    "baylor scott and white": "baylor scott and white - austin",
    "cedar park regional": "cedar park regional medical center",
}
