const crashDataMap = {
  active_school_zone_fl: "Active School Zone",
  approval_date: "Approval Date",
  approved_by: "Approved By",
  at_intrsct_fl: "Intersection-Relation Flag",
  case_id: "Case ID",
  crash_date: "Crash Date",
  crash_fatal_fl: "Fatality Flag",
  crash_id: "Crash ID",
  crash_sev_id: "Crash Severity ID",
  crash_speed_limit: "Speed Limit",
  crash_time: "Crash Time",
  day_of_week: "Day of Week",
  death_cnt: "Death Count",
  fhe_collsn_id: "Manner of Collision ID",
  geocode_date: "Geocode Date",
  geocode_provider: "Geocode Provider",
  geocode_status: "Geocode Status",
  geocoded: "Geocoded",
  hwy_nbr: "Highway Number",
  hwy_sfx: "Highway Suffix",
  hwy_sys: "Highway System",
  intrsct_relat_id: "Intersection Related ID",
  investigator_narrative: "Investigator Narrative",
  is_retired: "Is Retired",
  last_update: "Last Updated",
  latitude: "Latitude",
  latitude_confirmed: "Latitude Confirmed",
  latitude_geocoded: "Latitude Geocode",
  light_cond_id: "Light Condition",
  longitude: "Longitude",
  longitude_confirmed: "Longitude Confirmed",
  longitude_geocoded: "Longitude Geocoded",
  non_injry_cnt: "Not Injured Count",
  nonincap_injry_cnt: "Non-incapacitating Injury Count",
  obj_struck_id: "Object Struck ID",
  onsys_fl: "On TxDOT Highway System Flag",
  position: "Position",
  poss_injry_cnt: "Possible Injury Count",
  private_dr_fl: "Private Drive Flag",
  qa_status: "QA Status",
  road_constr_zone_fl: "Road Construction Zone flag",
  road_type_id: "Roadway Type ID",
  rpt_block_num: "Block Number",
  rpt_city_id: "City ID",
  rpt_hwy_num: "Highway Number",
  rpt_hwy_sfx: "Highway Suffix",
  rpt_latitude: "Reported Latitude",
  rpt_longitude: "Reported Longitude",
  rpt_outside_city_limit_fl: "Outside City Limit Flag",
  rpt_rdwy_sys_id: "Roadway System ID",
  rpt_road_part_id: "Roadway Part ID",
  rpt_sec_block_num: "Secondary Block Number",
  rpt_sec_hwy_num: "Secondary Highway Number",
  rpt_sec_hwy_sfx: "Secondary Highway Suffix",
  rpt_sec_rdwy_sys_id: "Secondary Roadway System ID",
  rpt_sec_road_part_id: "Secondary Roadway Part ID",
  rpt_sec_street_desc: "Secondary Street Description",
  rpt_sec_street_name: "Secondary Street Name",
  rpt_sec_street_pfx: "Secondary Street Prefix",
  rpt_sec_street_sfx: "Secondary Street Suffix",
  rpt_street_name: "Street Name",
  rpt_street_pfx: "Street Prefix",
  rpt_street_sfx: "Street Suffix",
  rr_relat_fl: "Railroad Related Flag",
  schl_bus_fl: "School Bus Flag",
  street_name: "Street Name",
  street_name_2: "Street Name 2",
  street_nbr: "Street Number",
  street_nbr_2: "Street Number 2",
  sus_serious_injry_cnt: "Suspected Serious Injury Count",
  toll_road_fl: "Toll Road/Lane Flag",
  tot_injry_cnt: "Total Injury Count",
  traffic_cntl_id: "Traffic Control ID",
  unkn_injry_cnt: "Unknown Injury Count",
  wthr_cond_id: "Weather Condition ID"
};

export default crashDataMap;
