create table public.crashes_cris (
    id serial primary key,
    active_school_zone_fl boolean,
    at_intrsct_fl boolean,
    case_id text,
    cr3_processed_at timestamp with time zone,
    cr3_stored_fl boolean not null default false,
    crash_speed_limit integer,
    crash_timestamp timestamp with time zone,
    cris_crash_id integer unique,
    cris_schema_version text not null,
    fhe_collsn_id integer references lookups.collsn_lkp (id) on update cascade on delete cascade,
    intrsct_relat_id integer references lookups.intrsct_relat_lkp (id) on update cascade on delete cascade,
    investigat_agency_id integer references lookups.agency_lkp (id) on update cascade on delete cascade,
    investigator_narrative text,
    is_deleted boolean not null default false,
    is_temp_record boolean not null default false,
    latitude numeric,
    light_cond_id integer references lookups.light_cond_lkp (id) on update cascade on delete cascade,
    longitude numeric,
    medical_advisory_fl boolean,
    obj_struck_id integer references lookups.obj_struck_lkp (id) on update cascade on delete cascade,
    onsys_fl boolean,
    private_dr_fl boolean,
    road_constr_zone_fl boolean,
    road_constr_zone_wrkr_fl boolean,
    rpt_block_num text,
    rpt_city_id integer references lookups.city_lkp (id) on update cascade on delete cascade,
    rpt_cris_cnty_id integer references lookups.cnty_lkp (id) on update cascade on delete cascade,
    rpt_hwy_num text,
    rpt_hwy_sfx text,
    rpt_rdwy_sys_id integer references lookups.rwy_sys_lkp (id) on update cascade on delete cascade,
    rpt_ref_mark_dir text,
    rpt_ref_mark_dist_uom text,
    rpt_ref_mark_nbr text,
    rpt_ref_mark_offset_amt numeric,
    rpt_road_part_id integer references lookups.road_part_lkp (id) on update cascade on delete cascade,
    rpt_sec_block_num text,
    rpt_sec_hwy_num text,
    rpt_sec_hwy_sfx text,
    rpt_sec_rdwy_sys_id integer references lookups.rwy_sys_lkp (id) on update cascade on delete cascade,
    rpt_sec_road_part_id integer references lookups.road_part_lkp (id) on update cascade on delete cascade,
    rpt_sec_street_desc text,
    rpt_sec_street_name text,
    rpt_sec_street_pfx text,
    rpt_sec_street_sfx text,
    rpt_street_desc text,
    rpt_street_name text,
    rpt_street_pfx text,
    rpt_street_sfx text,
    rr_relat_fl boolean,
    schl_bus_fl boolean,
    surf_cond_id integer references lookups.surf_cond_lkp (id) on update cascade on delete cascade,
    surf_type_id integer references lookups.surf_type_lkp (id) on update cascade on delete cascade,
    thousand_damage_fl boolean,
    toll_road_fl boolean,
    traffic_cntl_id integer references lookups.traffic_cntl_lkp (id) on update cascade on delete cascade,
    txdot_rptable_fl boolean,
    wthr_cond_id integer references lookups.wthr_cond_lkp (id) on update cascade on delete cascade
);

create table public.crashes_edits (
    id integer primary key references public.crashes_cris (id) on update cascade on delete cascade,
    active_school_zone_fl boolean,
    at_intrsct_fl boolean,
    case_id text,
    cr3_processed_at timestamp with time zone,
    cr3_stored_fl boolean,
    crash_speed_limit integer,
    crash_timestamp timestamp with time zone,
    cris_crash_id integer unique,
    fhe_collsn_id integer references lookups.collsn_lkp (id) on update cascade on delete cascade,
    intrsct_relat_id integer references lookups.intrsct_relat_lkp (id) on update cascade on delete cascade,
    investigat_agency_id integer references lookups.agency_lkp (id) on update cascade on delete cascade,
    investigator_narrative text,
    is_deleted boolean,
    is_temp_record boolean,
    latitude numeric,
    law_enforcement_ytd_fatality_num text,
    light_cond_id integer references lookups.light_cond_lkp (id) on update cascade on delete cascade,
    longitude numeric,
    medical_advisory_fl boolean,
    obj_struck_id integer references lookups.obj_struck_lkp (id) on update cascade on delete cascade,
    onsys_fl boolean,
    private_dr_fl boolean,
    road_constr_zone_fl boolean,
    road_constr_zone_wrkr_fl boolean,
    rpt_block_num text,
    rpt_city_id integer references lookups.city_lkp (id) on update cascade on delete cascade,
    rpt_cris_cnty_id integer references lookups.cnty_lkp (id) on update cascade on delete cascade,
    rpt_hwy_num text,
    rpt_hwy_sfx text,
    rpt_rdwy_sys_id integer references lookups.rwy_sys_lkp (id) on update cascade on delete cascade,
    rpt_ref_mark_dir text,
    rpt_ref_mark_dist_uom text,
    rpt_ref_mark_nbr text,
    rpt_ref_mark_offset_amt numeric,
    rpt_road_part_id integer references lookups.road_part_lkp (id) on update cascade on delete cascade,
    rpt_sec_block_num text,
    rpt_sec_hwy_num text,
    rpt_sec_hwy_sfx text,
    rpt_sec_rdwy_sys_id integer references lookups.rwy_sys_lkp (id) on update cascade on delete cascade,
    rpt_sec_road_part_id integer references lookups.road_part_lkp (id) on update cascade on delete cascade,
    rpt_sec_street_desc text,
    rpt_sec_street_name text,
    rpt_sec_street_pfx text,
    rpt_sec_street_sfx text,
    rpt_street_desc text,
    rpt_street_name text,
    rpt_street_pfx text,
    rpt_street_sfx text,
    rr_relat_fl boolean,
    schl_bus_fl boolean,
    surf_cond_id integer references lookups.surf_cond_lkp (id) on update cascade on delete cascade,
    surf_type_id integer references lookups.surf_type_lkp (id) on update cascade on delete cascade,
    thousand_damage_fl boolean,
    toll_road_fl boolean,
    traffic_cntl_id integer references lookups.traffic_cntl_lkp (id) on update cascade on delete cascade,
    txdot_rptable_fl boolean,
    wthr_cond_id integer references lookups.wthr_cond_lkp (id) on update cascade on delete cascade
);

create table public.crashes (
    id integer primary key references public.crashes_cris (id) on update cascade on delete cascade,
    active_school_zone_fl boolean,
    address_primary text generated always as (trim(coalesce(rpt_street_pfx, '') || ' ' || coalesce(rpt_block_num, '') || ' ' || coalesce(rpt_street_name, '') || ' ' || coalesce(rpt_street_sfx, ''))) stored,
    address_secondary text generated always as (trim(coalesce(rpt_sec_street_pfx, '') || ' ' || coalesce(rpt_sec_block_num, '') || ' ' || coalesce(rpt_sec_street_name, '') || ' ' || coalesce(rpt_sec_street_sfx, ''))) stored,
    at_intrsct_fl boolean,
    case_id text,
    council_district integer,
    cr3_processed_at timestamp with time zone,
    cr3_stored_fl boolean not null default false,
    crash_speed_limit integer,
    crash_timestamp timestamp with time zone,
    cris_crash_id integer unique,
    engineering_area integer references public.engineering_areas (area_id) on update cascade on delete set null,
    fhe_collsn_id integer references lookups.collsn_lkp (id) on update cascade on delete cascade,
    in_austin_full_purpose boolean,
    intrsct_relat_id integer references lookups.intrsct_relat_lkp (id) on update cascade on delete cascade,
    investigat_agency_id integer references lookups.agency_lkp (id) on update cascade on delete cascade,
    investigator_narrative text,
    is_deleted boolean not null default false,
    is_temp_record boolean not null default false,
    latitude numeric,
    law_enforcement_ytd_fatality_num text,
    light_cond_id integer references lookups.light_cond_lkp (id) on update cascade on delete cascade,
    location_id text references public.atd_txdot_locations (location_id) on update cascade on delete set null,
    longitude numeric,
    medical_advisory_fl boolean,
    obj_struck_id integer references lookups.obj_struck_lkp (id) on update cascade on delete cascade,
    onsys_fl boolean,
    position geometry(Point, 4326),
    private_dr_fl boolean,
    record_locator text unique not null generated always as (case when is_temp_record = true then 'T' || id::text  else cris_crash_id::text end) stored,
    road_constr_zone_fl boolean,
    road_constr_zone_wrkr_fl boolean,
    rpt_block_num text,
    rpt_city_id integer references lookups.city_lkp (id) on update cascade on delete cascade,
    rpt_cris_cnty_id integer references lookups.cnty_lkp (id) on update cascade on delete cascade,
    rpt_hwy_num text,
    rpt_hwy_sfx text,
    rpt_rdwy_sys_id integer references lookups.rwy_sys_lkp (id) on update cascade on delete cascade,
    rpt_ref_mark_dir text,
    rpt_ref_mark_dist_uom text,
    rpt_ref_mark_nbr text,
    rpt_ref_mark_offset_amt numeric,
    rpt_road_part_id integer references lookups.road_part_lkp (id) on update cascade on delete cascade,
    rpt_sec_block_num text,
    rpt_sec_hwy_num text,
    rpt_sec_hwy_sfx text,
    rpt_sec_rdwy_sys_id integer references lookups.rwy_sys_lkp (id) on update cascade on delete cascade,
    rpt_sec_road_part_id integer references lookups.road_part_lkp (id) on update cascade on delete cascade,
    rpt_sec_street_desc text,
    rpt_sec_street_name text,
    rpt_sec_street_pfx text,
    rpt_sec_street_sfx text,
    rpt_street_desc text,
    rpt_street_name text,
    rpt_street_pfx text,
    rpt_street_sfx text,
    rr_relat_fl boolean,
    schl_bus_fl boolean,
    surf_cond_id integer references lookups.surf_cond_lkp (id) on update cascade on delete cascade,
    surf_type_id integer references lookups.surf_type_lkp (id) on update cascade on delete cascade,
    thousand_damage_fl boolean,
    toll_road_fl boolean,
    traffic_cntl_id integer references lookups.traffic_cntl_lkp (id) on update cascade on delete cascade,
    txdot_rptable_fl boolean,
    wthr_cond_id integer references lookups.wthr_cond_lkp (id) on update cascade on delete cascade
);
