export type EmsCrashesListRow = {
  record_id: string;
  record_table_name: "crashes" | "ems__incidents";
  record_locator: string;
  case_id: string | null;
  details_page: string;
  record_responding_agency: string | null;
  record_timestamp: string | null;
  record_date_ct: string | null;
  record_time_ct: string | null;
  record_day_of_week: string | null;
  record_address: string | null;
  latitude: number | null;
  longitude: number | null;
  location_id: string | null;
  in_austin_full_purpose: boolean | null;
  units_involved: string | null;
  has_ems_override: boolean | null;
  injured_people_match_status: "fully_matched" | "unmatched" | "mixed" | null;
  unkn_injry_count: number | null;
  nonincap_injry_count: number | null;
  poss_injry_count: number | null;
  non_injry_count: number | null;
  sus_serious_injry_count: number | null;
  tot_injry_count: number | null;
  fatality_count: number | null;
  vz_fatality_count: number | null;
  law_enf_fatality_count: number | null;
  cris_fatality_count: number | null;
  motor_vehicle_fatality_count: number | null;
  motor_vehicle_sus_serious_injry_count: number | null;
  motorcycle_fatality_count: number | null;
  motorcycle_sus_serious_count: number | null;
  bicycle_fatality_count: number | null;
  bicycle_sus_serious_injry_count: number | null;
  pedestrian_fatality_count: number | null;
  pedestrian_sus_serious_injry_count: number | null;
  micromobility_fatality_count: number | null;
  micromobility_sus_serious_injry_count: number | null;
  other_fatality_count: number | null;
  other_sus_serious_injry_count: number | null;
  crash_injry_sev_id: number | null;
  crash_injry_sev_desc: string | null;
  years_of_life_lost: number | null;
  est_comp_cost_crash_based: number | null;
  est_total_person_comp_cost: number | null;
};
