import { CrashInjuryMetric } from "@/types/crashInjuryMetrics";
import { LookupTableOption } from "@/types/relationships";
import { ChangeLogEntry } from "@/types/changeLog";
import { Unit } from "@/types/unit";
import { Charge } from "@/types/charge";
import { PeopleListRow } from "@/types/peopleList";
import { Recommendation } from "@/types/recommendation";
import { CrashesListRow } from "@/types/crashesList";
import { CrashNote } from "./crashNote";
import { EMSPatientCareRecord } from "@/types/ems";

export type Crash = {
  active_school_zone_fl: boolean | null;
  at_intrsct_fl: boolean | null;
  case_id: string | null;
  crash_injury_metrics_view: CrashInjuryMetric | null;
  crash_notes: CrashNote[];
  cr3_stored_fl: boolean | null;
  crash_speed_limit: number | null;
  crash_timestamp: string | null;
  cris_crash_id: number | null;
  collsn: LookupTableOption | null;
  ems__incidents: EMSPatientCareRecord[] | null;
  fhe_collsn_id: number | null;
  id: number;
  in_austin_full_purpose: boolean;
  investigator_narrative: string | null;
  is_temp_record: boolean | null;
  latitude: number | null;
  law_enforcement_ytd_fatality_num: string | null;
  light_cond_id: number | null;
  light_cond: LookupTableOption | null;
  location_id: string | null;
  longitude: number | null;
  obj_struck_id: number | null;
  obj_struck: LookupTableOption | null;
  onsys_fl: boolean | null;
  private_dr_fl: boolean | null;
  record_locator: string;
  recommendation: Recommendation | null;
  road_constr_zone_fl: boolean | null;
  rpt_block_num: string | null;
  rpt_city_id: number | null;
  city: LookupTableOption | null;
  rpt_hwy_num: string | null;
  rpt_rdwy_sys_id: number | null;
  rwy_sys: LookupTableOption | null;
  rpt_road_part_id: number | null;
  road_part: LookupTableOption | null;
  rpt_sec_block_num: string | null;
  rpt_sec_hwy_num: string | null;
  rpt_sec_rdwy_sys_id: number | null;
  rwy_sys_sec: LookupTableOption | null;
  rpt_sec_road_part_id: number | null;
  road_part_sec: LookupTableOption | null;
  rpt_sec_street_desc: string | null;
  rpt_sec_street_name: string | null;
  rpt_sec_street_pfx: string | null;
  rpt_sec_street_sfx: string | null;
  rpt_sec_hwy_sfx: string | null;
  rpt_street_desc: string | null;
  rpt_street_name: string | null;
  rpt_street_pfx: string | null;
  rpt_street_sfx: string | null;
  rpt_hwy_sfx: string | null;
  rr_relat_fl: boolean | null;
  schl_bus_fl: boolean | null;
  toll_road_fl: boolean | null;
  traffic_cntl_id: number | null;
  updated_at: string | null;
  updated_by: string | null;
  wthr_cond_id: number | null;
  change_logs: ChangeLogEntry[] | null;
  units: Unit[] | null;
  charges_cris: Charge[] | null;
  people_list_view: PeopleListRow[] | null;
  crashes_list_view: CrashesListRow;
  address_display: string | null;
};
