export type CrashesListRow = {
  case_id: string | null;
  collsn_desc: string | null;
  council_district: number | null;
  crash_date_ct: string;
  crash_day_of_week: string;
  crash_injry_sev_desc: string | null;
  crash_speed_limit: number | null;
  crash_time_ct: string;
  crash_timestamp: string;
  cris_crash_id: number | null;
  cris_fatality_count: number | null;
  est_comp_cost_crash_based: number | null;
  intrsct_relat_id: number | null;
  latitude: number | null;
  light_cond_id: number | null;
  longitude: number | null;
  non_injry_count: number | null;
  nonincap_injry_count: number | null;
  obj_struck_id: number | null;
  onsys_fl: boolean | null;
  poss_injry_count: number | null;
  private_dr_fl: boolean | null;
  record_locator: string;
  road_constr_zone_fl: boolean | null;
  rpt_block_num: string | null;
  rpt_sec_block_num: string | null;
  rpt_sec_street_name: string | null;
  rpt_sec_street_pfx: string | null;
  rpt_street_name: string | null;
  rpt_street_pfx: string | null;
  rr_relat_fl: boolean | null;
  schl_bus_fl: boolean | null;
  sus_serious_injry_count: number | null;
  toll_road_fl: boolean | null;
  traffic_cntl_id: number | null;
  unkn_injry_count: number | null;
  vz_fatality_count: number | null;
  wthr_cond_id: number | null;
  is_manual_geocode: boolean | null;
  address_display: string | null;
};
