import { z } from "zod";
import { lookupOptionSchema } from "./lookupTable";
import { unitSchema } from "./units";
import { changeLogEntrySchema } from "./changeLog";

export const crashSchema = z.object({
  active_school_zone_fl: z.number().nullable(),
  address_primary: z.string().nullable(),
  address_secondary: z.string().nullable(),
  at_intrsct_fl: z.boolean().nullable(),
  case_id: z.string().nullable(),
  cr3_stored_fl: z.boolean().nullable(),
  crash_speed_limit: z.number().nullable(),
  crash_timestamp: z.string().nullable(),
  cris_crash_id: z.number().nullable(),
  collsn: lookupOptionSchema,
  fhe_collsn_id: z.number().nullable(),
  id: z.number(),
  in_austin_full_purpose: z.boolean(),
  investigator_narrative: z.string().nullable(),
  is_temp_record: z.boolean().nullable(),
  latitude: z.number().nullable(),
  law_enforcement_ytd_fatality_num: z.string().nullable(),
  light_cond_id: z.number().nullable(),
  location_id: z.string().nullable(),
  longitude: z.number().nullable(),
  obj_struck_id: z.number().nullable(),
  obj_struck: lookupOptionSchema,
  onsys_fl: z.boolean().nullable(),
  private_dr_fl: z.boolean().nullable(),
  record_locator: z.string(),
  road_constr_zone_fl: z.boolean().nullable(),
  rpt_block_num: z.string().nullable(),
  rpt_city_id: z.number().nullable(),
  rpt_hwy_num: z.string().nullable(),
  rpt_rdwy_sys_id: z.number().nullable(),
  rpt_road_part_id: z.number().nullable(),
  rpt_sec_block_num: z.string().nullable(),
  rpt_sec_hwy_num: z.string().nullable(),
  rpt_sec_rdwy_sys_id: z.number().nullable(),
  rpt_sec_road_part_id: z.number().nullable(),
  rpt_sec_street_desc: z.string().nullable(),
  rpt_sec_street_name: z.string().nullable(),
  rpt_sec_street_pfx: z.string().nullable(),
  rpt_sec_street_sfx: z.string().nullable(),
  rpt_street_desc: z.string().nullable(),
  rpt_street_name: z.string().nullable(),
  rpt_street_pfx: z.string().nullable(),
  rpt_street_sfx: z.string().nullable(),
  rr_relat_fl: z.boolean().nullable(),
  schl_bus_fl: z.boolean().nullable(),
  toll_road_fl: z.boolean().nullable(),
  traffic_cntl_id: z.number().nullable(),
  updated_at: z.string().nullable(),
  updated_by: z.string().nullable(),
  wthr_cond_id: z.number().nullable(),
  change_logs: z.array(changeLogEntrySchema),
  units: z.array(unitSchema),
});
