delete from lookups.agency where id = 10237;
delete from lookups.agency where id = 10238;
delete from lookups.agency where id = 11200;
delete from lookups.agency where id = 3384;
delete from lookups.agency where id = 3385;
delete from lookups.agency where id = 3386;
delete from lookups.agency where id = 3387;
delete from lookups.agency where id = 3388;
delete from lookups.agency where id = 3389;
delete from lookups.agency where id = 3390;
delete from lookups.agency where id = 3391;
delete from lookups.agency where id = 3392;
delete from lookups.agency where id = 3393;
delete from lookups.agency where id = 3394;
insert into lookups.agency (id, label, source) values (114, 'BENAVIDES POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1203, 'DICKENS COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (1211, 'DONLEY COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (1252, 'EL CENIZO POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1335, 'GAINES COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (1382, 'GRAYSON COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (1416, 'HARLANDALE ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1487, 'HOWARD COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (1621, 'LADONIA POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1705, 'LUBBOCK ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1749, 'MAUD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (2057, 'RUSK COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (2133, 'SMITH COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (2184, 'STONEWALL COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (2228, 'TEXARKANA COLLEGE POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (2429, 'WILLACY COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (2507, 'BANDERA COUNTY CONSTABLE PRECINCT 4', 'cris');
insert into lookups.agency (id, label, source) values (2521, 'BEXAR COUNTY CONSTABLE PRECINCT 3', 'cris');
insert into lookups.agency (id, label, source) values (31, 'AMARILLO AIRPORT POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3178, 'DALWORTHINGTON GARDENS DEPARTMENT OF PUBLIC SAFETY', 'cris');
insert into lookups.agency (id, label, source) values (3209, 'PALESTINE CITY MARSHAL''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (44, 'ANGLETON ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (55, 'ARCHER COUNTY SHERIFF''S OFFICE', 'cris');
