-- Add crash notes about removal of agency ID 2429
WITH crashes_to_update AS (
    SELECT id FROM crashes WHERE investigat_agency_id = 2429
)
INSERT INTO crash_notes (crash_pk, text, created_by, updated_by)
SELECT
    id,
    'Removed investigat_agency_id ID 2429 which was deprecated by CRIS v29.1.1',
    'dts_automation',
    'dts_automation'
FROM crashes_to_update;
-- nullify use of agency ID 2429
UPDATE crashes_cris SET investigat_agency_id = NULL, updated_by = 'dts_automation'
WHERE investigat_agency_id = 2429;

--
-- Migrations generated by helper script
--
DELETE FROM lookups.agency WHERE id = 114;
DELETE FROM lookups.agency WHERE id = 1203;
DELETE FROM lookups.agency WHERE id = 1211;
DELETE FROM lookups.agency WHERE id = 1252;
DELETE FROM lookups.agency WHERE id = 1335;
DELETE FROM lookups.agency WHERE id = 1382;
DELETE FROM lookups.agency WHERE id = 1416;
DELETE FROM lookups.agency WHERE id = 1487;
DELETE FROM lookups.agency WHERE id = 1621;
DELETE FROM lookups.agency WHERE id = 1705;
DELETE FROM lookups.agency WHERE id = 1749;
DELETE FROM lookups.agency WHERE id = 2057;
DELETE FROM lookups.agency WHERE id = 2133;
DELETE FROM lookups.agency WHERE id = 2184;
DELETE FROM lookups.agency WHERE id = 2228;
DELETE FROM lookups.agency WHERE id = 2429;
DELETE FROM lookups.agency WHERE id = 2507;
DELETE FROM lookups.agency WHERE id = 2521;
DELETE FROM lookups.agency WHERE id = 3178;
DELETE FROM lookups.agency WHERE id = 31;
DELETE FROM lookups.agency WHERE id = 3209;
DELETE FROM lookups.agency WHERE id = 44;
DELETE FROM lookups.agency WHERE id = 55;
INSERT INTO lookups.agency (id, label, source) VALUES (
    10237, 'CITY OF AUSTIN', 'cris'
);
INSERT INTO lookups.agency (id, label, source) VALUES (
    10238, 'EAGLE PASS METROPOLITAN PLANNING ORGANIZATION', 'cris'
);
INSERT INTO lookups.agency (id, label, source) VALUES (
    11200, 'PURCHASE USERS', 'cris'
);
INSERT INTO lookups.agency (id, label, source) VALUES (
    3384,
    'TRAVIS COUNTY - TRANSPORTATION AND NATURAL RESOURCES - PARKS POLICE',
    'cris'
);
INSERT INTO lookups.agency (id, label, source) VALUES (
    3385, 'HILLCREST VILLAGE MARSHAL''S OFFICE', 'cris'
);
INSERT INTO lookups.agency (id, label, source) VALUES (
    3386, 'ITASCA POLICE DEPARTMENT', 'cris'
);
INSERT INTO lookups.agency (id, label, source) VALUES (
    3387, 'LEON COUNTY CONSTABLE PCT 2', 'cris'
);
INSERT INTO lookups.agency (id, label, source) VALUES (
    3388, 'FANNIN COUNTY CONSTABLE PRECINCT 2', 'cris'
);
INSERT INTO lookups.agency (id, label, source) VALUES (
    3389, 'ROBERTSON COUNTY SHERIFF''S OFFICE', 'cris'
);
INSERT INTO lookups.agency (id, label, source) VALUES (
    3390, 'PEWITT CISD POLICE DEPARTMENT', 'cris'
);
INSERT INTO lookups.agency (id, label, source) VALUES (
    3391, 'HARRIS COUNTY FIRE MARSHAL OFFICE', 'cris'
);
INSERT INTO lookups.agency (id, label, source) VALUES (
    3392, 'ALEDO POLICE DEPARTMENT', 'cris'
);
INSERT INTO lookups.agency (id, label, source) VALUES (
    3393, 'GALVESTON COUNTY CONSTABLE OFFICE PRECINCT 1', 'cris'
);
INSERT INTO lookups.agency (id, label, source) VALUES (
    3394, 'VAN ALSTYNE ISD POLICE DEPARTMENT', 'cris'
);
