delete from lookups.agency where id = 114;
delete from lookups.agency where id = 1203;
delete from lookups.agency where id = 1211;
delete from lookups.agency where id = 1252;
delete from lookups.agency where id = 1335;
delete from lookups.agency where id = 1382;
delete from lookups.agency where id = 1416;
delete from lookups.agency where id = 1487;
delete from lookups.agency where id = 1621;
delete from lookups.agency where id = 1705;
delete from lookups.agency where id = 1749;
delete from lookups.agency where id = 2057;
delete from lookups.agency where id = 2133;
delete from lookups.agency where id = 2184;
delete from lookups.agency where id = 2228;
delete from lookups.agency where id = 2429;
delete from lookups.agency where id = 2507;
delete from lookups.agency where id = 2521;
delete from lookups.agency where id = 3178;
delete from lookups.agency where id = 31;
delete from lookups.agency where id = 3209;
delete from lookups.agency where id = 44;
delete from lookups.agency where id = 55;
insert into lookups.agency (id, label, source) values (10237, 'CITY OF AUSTIN', 'cris');
insert into lookups.agency (id, label, source) values (10238, 'EAGLE PASS METROPOLITAN PLANNING ORGANIZATION', 'cris');
insert into lookups.agency (id, label, source) values (11200, 'PURCHASE USERS', 'cris');
insert into lookups.agency (id, label, source) values (3384, 'TRAVIS COUNTY - TRANSPORTATION AND NATURAL RESOURCES - PARKS POLICE', 'cris');
insert into lookups.agency (id, label, source) values (3385, 'HILLCREST VILLAGE MARSHAL''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (3386, 'ITASCA POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3387, 'LEON COUNTY CONSTABLE PCT 2', 'cris');
insert into lookups.agency (id, label, source) values (3388, 'FANNIN COUNTY CONSTABLE PRECINCT 2', 'cris');
insert into lookups.agency (id, label, source) values (3389, 'ROBERTSON COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (3390, 'PEWITT CISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3391, 'HARRIS COUNTY FIRE MARSHAL OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (3392, 'ALEDO POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3393, 'GALVESTON COUNTY CONSTABLE OFFICE PRECINCT 1', 'cris');
insert into lookups.agency (id, label, source) values (3394, 'VAN ALSTYNE ISD POLICE DEPARTMENT', 'cris');
