COLUMNS = {
    "ems": {
        "cols_to_rename": {
            "mvc_form_extrication_time": "mvc_form_extrication_datetime"
        },
        "update_columns": [
            "pcr_key",
            "incident_date_received",
            "incident_time_received",
            "incident_number",
            "incident_location_address",
            "incident_location_city",
            "incident_location_state",
            "incident_location_zip",
            "incident_location_longitude",
            "incident_location_latitude",
            "incident_problem",
            "incident_priority_number",
            "pcr_cause_of_injury",
            "pcr_patient_complaints",
            "pcr_provider_impression_primary",
            "pcr_provider_impression_secondary",
            "pcr_outcome",
            "pcr_transport_destination",
            "pcr_patient_acuity_level",
            "pcr_patient_acuity_level_reason",
            "pcr_patient_age",
            "pcr_patient_gender",
            "pcr_patient_race",
            "mvc_form_airbag_deployment",
            "mvc_form_airbag_deployment_status",
            "mvc_form_collision_indicators",
            "mvc_form_damage_location",
            "mvc_form_estimated_speed_kph",
            "mvc_form_estimated_speed_mph",
            "mvc_form_extrication_comments",
            "mvc_form_extrication_datetime",
            "mvc_form_extrication_required_flag",
            "mvc_form_patient_injured_flag",
            "mvc_form_position_in_vehicle",
            "mvc_form_safety_devices",
            "mvc_form_seat_row_number",
            "mvc_form_vehicle_type",
            "mvc_form_weather",
            "pcr_additional_agencies",
            "pcr_transport_priority",
            "pcr_patient_acuity_initial",
            "pcr_patient_acuity_final",
            "unparsed_apd_incident_numbers",
            "apd_incident_numbers",
            "latitude",
            "longitude",
        ],
    },
    "afd": {
        "cols_to_rename": {},
        "update_columns": [
            "unparsed_ems_incident_number",
            "ems_incident_numbers",
            "call_datetime",
            "calendar_year",
            "jurisdiction",
            "address",
            "problem",
            "flagged_incs",
            "geometry",
            "latitude",
            "longitude",
        ],
    },
}
