[build]
  publish = "build"
  command = "echo 'Environment not recognized'"

# Production specific build command
[context.production]
  command = "npm run lint && npm run build:production"

# Staging specific build command
[context.main]
  command = "npm run lint && npm run build:staging"

# Deploy previews use staging environment
[context.deploy-preview]
  command = "npm run lint && npm run build:staging"

# This rule handles the root path and redirects to /viewer/
[[redirects]]
  from = "/"
  to = "/viewer/"
  status = 302

# Redirect to the index page of the SPA
[[redirects]]
  from = "/viewer/*"
  to = "/viewer/index.html"
  status = 200