alter table ems__incidents
    add column flag_patient_age_estimated numeric,
    add column flag_patient_deceased numeric,
    add column flag_patient_gcs_lte_13 numeric,
    add column pcr_alcohol_drug_usage text,
    add column pcr_injury_mechanism text,
    add column pcr_injury_place text,
    add column pcr_injury_primary text,
    add column pcr_patient_care_transferred_to text,
    add column pcr_patient_condition_at_destination text,
    add column pcr_patient_injured text,
    add column trauma_form_criteria_injury_mechanisms text,
    add column trauma_form_criteria_injury_patterns text,
    add column trauma_form_criteria_provider_judgement text,
    add column trauma_form_criteria_vital_signs text,
    add column trauma_form_trauma_activation numeric,
    add column trauma_form_trauma_level text,
    add column trauma_form_trauma_level_description text;

comment on column ems__incidents.id is 'Primary key - ID sequence generated by database';
comment on column ems__incidents.incident_problem is 'The ''call type'' or reason for the incident. Determined by communications staff while processing the 911 call. Also known as ""Call Type"", ""Incident Type"", ""Problem Type"", ""Call Nature""';
comment on column ems__incidents.incident_priority_number is 'The ''priority'' of the incident. Determined by communications staff while processing the incident. 1 = Emergent, 2-3 = Urgent, 4+ = Non-Urgent';
comment on column ems__incidents.pcr_cause_of_injury is 'Cause of the patients injury as documented by the EMS provider in the patient care report (PCR)';
comment on column ems__incidents.pcr_patient_complaints is 'Patient complaints (ie signs and symptoms) as documented by the EMS provider in the patient care report (PCR)';
comment on column ems__incidents.pcr_provider_impression_primary is 'EMS provider''s primary impression of the patient''s condition, documented in the PCR';
comment on column ems__incidents.pcr_provider_impression_secondary is 'EMS provider''s supporting impression of the patient''s condition, documented in the PCR';
comment on column ems__incidents.pcr_outcome is 'High level outcome (aka Disposition) of the patient encounter (ie Transported, Refused, etc). Documented in the PCR';
comment on column ems__incidents.pcr_transport_destination is 'The name of the hospital that the patient was transported to, if applicable. Documented in the PCR';
comment on column ems__incidents.pcr_patient_acuity_level is 'Calculated patient acuity based on interventions (treatments), vital signs, primary impressions, and patient alerts as documented by the EMS provider in the PCR';
comment on column ems__incidents.pcr_patient_acuity_level_reason is 'The reason that the PCR was determined as ""High Acuity"" (eg Interventions, Vital Signs, Alerts, etc)';
comment on column ems__incidents.pcr_patient_age is 'The calculated age of the patient at the time of the patient encounter. Calculation based on patient date of birth or estimated age documented by EMS provider in the PCR';
comment on column ems__incidents.pcr_patient_gender is 'The patient''s gender as documented by the EMS provider in the PCR';
comment on column ems__incidents.pcr_patient_race is 'The patient''s race as documented by the EMS provider in the PCR';
comment on column ems__incidents.mvc_form_airbag_deployment is 'PCR Form - MVC: List of which airbags were deployed';
comment on column ems__incidents.mvc_form_airbag_deployment_status is 'PCR Form - MVC: Status of airbag deployment (ie deployed or not)';
comment on column ems__incidents.mvc_form_collision_indicators is 'PCR Form - MVC: List of collision indicators';
comment on column ems__incidents.mvc_form_damage_location is 'PCR Form - MVC: List of locations on the vehicle that have damage';
comment on column ems__incidents.mvc_form_estimated_speed_kph is 'PCR Form - MVC: Estimated speed of the vehicle at time of collision, in kph';
comment on column ems__incidents.mvc_form_estimated_speed_mph is 'PCR Form - MVC: Estimated speed of the vehicle at time of collision, in mph';
comment on column ems__incidents.mvc_form_extrication_comments is 'PCR Form - MVC: EMS provider comments about extrication, such as reasons for extrication, patient location, etc';
comment on column ems__incidents.mvc_form_extrication_required_flag is 'PCR Form - MVC: Indicates whether the patient needed to be extracted from the vehicle (ie due to entrapment etc) (1 = Yes)';
comment on column ems__incidents.mvc_form_patient_injured_flag is 'PCR Form - MVC: Indicates whether the patient was injured (1 = Yes)';
comment on column ems__incidents.mvc_form_position_in_vehicle is 'PCR Form - MVC: Where the patient was positioned in the vehicle at the time of the collision, (eg front right seat, left rear seat, etc)';
comment on column ems__incidents.mvc_form_safety_devices is 'PCR Form - MVC: List of safety devices that were in use by the patient at the time of the collision (eg shoulder/lap belt, car seat, helmet, etc)';
comment on column ems__incidents.mvc_form_seat_row_number is 'PCR Form - MVC: Row number of the seat occupied by the patient in the vehicle at the time of the collision';
comment on column ems__incidents.mvc_form_vehicle_type is 'PCR Form - MVC: The type of vehicle that the patient was in at the time of the collision (eg Automobile, ATV, Motorcycle, etc)';
comment on column ems__incidents.mvc_form_weather is 'PCR Form - MVC: General description of the weather at the time of the collision (eg Clear, Rain, Overcast, etc)';
comment on column ems__incidents.pcr_additional_agencies is 'A comma-delimmted list of agency types that were also on scene for the incident, as documented by the EMS provider in the PCR';
comment on column ems__incidents.pcr_transport_priority is 'The transport priority if applicable. Typically this will be Code 1 (no lights/sirens) or Code 3 (lights and sirens), and can generally be used to determine the urgency of the transport. Other (legacy) transport priorities may include specific transport priority levels (such as Alpha, Bravo, Charlie, Delta, and Echo), which may be prefixed/suffixed with a ''3'' to indicate Code 3 transport. Transport priority levels without a ''3'' prefix/suffix should be considered Code 1 transports (no lights/sirens)';
comment on column ems__incidents.pcr_patient_acuity_initial is 'The patient acuity level at the start of the patient encounter, as determined and documented by the EMS provider at in the PCR. Note: this is different than the calculated Acuity Level that is based on documented procedures/vitals, etc';
comment on column ems__incidents.pcr_patient_acuity_final is 'The patient acuity level at the end of the patient encounter, as determined and documented by the EMS provider in the PCR. Note: this is different than the calculated Acuity Level that is based on documented procedures/vitals, etc';
comment on column ems__incidents.unparsed_apd_incident_numbers is 'The raw comma-delimitted string of APD case IDs that potentially match this incident. Potential matching is simply based on the time the incident was dispatched';
comment on column ems__incidents.apd_incident_numbers is 'A list of all APD case IDs linked to the EMS incident, whether directly or indirectly. Potential matching is simply based on the time the incident was dispatched';
comment on column ems__incidents.geometry is 'PostGIS geometry column generated automatically from the incidnet latitude and longitude';
comment on column ems__incidents.austin_full_purpose is 'If the incident occured within the Austin Full Purpose jurisdiction, as determined by intersecting the incident geometry with the geo.jurisdictions layer';
comment on column ems__incidents.location_id is 'Foreign key referencing the locations.location_id of the location polygon that intersects with the incident geomtery';
comment on column ems__incidents.latitude is 'The incident latitude';
comment on column ems__incidents.longitude is 'The incident longitude';
comment on column ems__incidents.mvc_form_extrication_datetime is 'PCR Form - MVC: The time patient extrication was performed , if applicable';
comment on column ems__incidents.incident_received_datetime is 'The date and time that the incident was received by EMS';
comment on column ems__incidents.created_at is 'The timestamp at which this record was created in the Vision Zero database';
comment on column ems__incidents.updated_at is 'The timestamp at which this record was last updated in the Vision Zero database. Set via trigger';
comment on column ems__incidents.flag_patient_age_estimated is 'Indicates whether the patient''s age was estimated by the EMS provider';
comment on column ems__incidents.flag_patient_deceased is 'Indicates whether the patient was deceased. Based on ""pronouncement"" disposition or treatment, or documented time of death';
comment on column ems__incidents.flag_patient_gcs_lte_13 is 'Indicates whether the patient''s Glasgow Coma Score was less than or equal to 13 at any time during the patient encounter';
comment on column ems__incidents.pcr_alcohol_drug_usage is 'List of indications of alcohol or drug use by the patient, as documented by the EMS provider in the PCR';
comment on column ems__incidents.pcr_injury_mechanism is 'General description of the mechanism of the patients injury (eg Blunt, Burn, Penetrating, etc)';
comment on column ems__incidents.pcr_injury_place is 'General description of the type of location where the patient was injured as documented by the EMS provider in the PCR';
comment on column ems__incidents.pcr_injury_primary is 'General description of how the patient was injured (eg Motorvehicle Accident, Bicycle Accident, etc)';
comment on column ems__incidents.pcr_patient_care_transferred_to is 'The agency or agency type that patient care was transferred to, in cases where the EMS provider(s) transferred care to another unit or agency';
comment on column ems__incidents.pcr_patient_condition_at_destination is 'General description of the patient''s condition on arriving at the transport destination, if applicable';
comment on column ems__incidents.pcr_patient_injured is 'General description of the patient''s condition on arriving at the transport destination, if applicable';
comment on column ems__incidents.trauma_form_criteria_injury_mechanisms is 'PCR Form - Trauma: List of present mechanisms of injury associated with trauma triage';
comment on column ems__incidents.trauma_form_criteria_injury_patterns is 'PCR Form - Trauma: List of present injury patterns associated with trauma triage';
comment on column ems__incidents.trauma_form_criteria_provider_judgement is 'PCR Form - Trauma: List of provider judgements, special considerations associated with trauma triage';
comment on column ems__incidents.trauma_form_criteria_vital_signs is 'PCR Form - Trauma: List of present vital signs or level of consciousness associated with trauma triage';
comment on column ems__incidents.trauma_form_trauma_activation is 'PCR Form - Trauma: Indicates whether there was a Trauma Activation';
comment on column ems__incidents.trauma_form_trauma_level is 'PCR Form - Trauma: Trauma level. Note: Trauma levels changed from 1 through 4 to Red and Yellow';
comment on column ems__incidents.trauma_form_trauma_level_description is 'PCR Form - Trauma: Description of the trauma level';
comment on column ems__incidents.is_deleted is 'If the record is deleted and should be ignored';
comment on column ems__incidents.created_by is 'The username or email address of the entity that created this record in the Vision Zero database';
comment on column ems__incidents.updated_by is 'The username or email address of the entity that last updated this record in the Vision Zero database';
