-- Changes to table atd_txdot__agency_lkp
update public.atd_txdot__agency_lkp set agency_desc = 'HOUSTON CHRISTIAN UNIVERSITY POLICE DEPARTMENT' where agency_id = 1478;
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (3339, 'WALKER COUNTY SHERIFF''S OFFICE');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (3340, 'EDGEWOOD POLICE DEPARTMENT');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (3341, 'SMILEY CITY MARSHAL''S OFFICE');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (3342, 'SHEPHERD POLICE DEPARTMENT');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (3343, 'HEMPSTEAD ISD POLICE DEPARTMENT');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (3344, 'HALE CENTER POLICE DEPARTMENT');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (3345, 'SALADO INDEPENDENT SCHOOL DISTRICT POLICE DEPARTMENT');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (3346, 'WILLS POINT ISD POLICE DEPARTMENT');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (3347, 'MAUD ISD POLICE DEPARTMENT');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (3348, 'FROST POLICE DEPARTMENT');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (3349, 'SCURRY-ROSSER ISD POLICE DEPARTMENT');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (3350, 'JARRELL ISD POLICE DEPARTMENT');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (3351, 'PORT ARTHUR ISD POLICE DEPARTMENT');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (3352, 'COOPER ISD POLICE DEPARTMENT');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (10221, 'CITY OF MESQUITE');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (10222, 'CITY OF ARLINGTON');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (10223, 'TOM GREEN COUNTY');
insert into public.atd_txdot__agency_lkp (agency_id, agency_desc) values (10224, 'FORT BEND COUNTY DISTRICT ATTORNEY''S OFFICE');

-- Changes to table atd_txdot__autonomous_level_engaged_lkp
insert into public.atd_txdot__autonomous_level_engaged_lkp (autonomous_level_engaged_id, autonomous_level_engaged_desc) values (3, 'CONDITIONAL AUTOMATION');
insert into public.atd_txdot__autonomous_level_engaged_lkp (autonomous_level_engaged_id, autonomous_level_engaged_desc) values (4, 'HIGH AUTOMATION');
insert into public.atd_txdot__autonomous_level_engaged_lkp (autonomous_level_engaged_id, autonomous_level_engaged_desc) values (5, 'FULL AUTOMATION');
update public.atd_txdot__autonomous_level_engaged_lkp set autonomous_level_engaged_desc = 'AUTOMATION LEVEL UNKNOWN' where autonomous_level_engaged_id = 6;

-- Changes to table atd_txdot__drvr_lic_cls_lkp
update public.atd_txdot__drvr_lic_cls_lkp set drvr_lic_cls_desc = 'AUTONOMOUS' where drvr_lic_cls_id = 95;

-- Changes to table atd_txdot__drvr_lic_endors_lkp
update public.atd_txdot__drvr_lic_endors_lkp set drvr_lic_endors_desc = 'AUTONOMOUS' where drvr_lic_endors_id = 95;

-- Changes to table atd_txdot__drvr_lic_restric_lkp
update public.atd_txdot__drvr_lic_restric_lkp set drvr_lic_restric_desc = 'AUTONOMOUS' where drvr_lic_restric_id = 95;

-- Changes to table atd_txdot__drvr_lic_type_lkp
update public.atd_txdot__drvr_lic_type_lkp set drvr_lic_type_desc = 'AUTONOMOUS' where drvr_lic_type_id = 95;

-- Changes to table atd_txdot__ethnicity_lkp
update public.atd_txdot__ethnicity_lkp set ethnicity_desc = 'AUTONOMOUS' where ethnicity_id = 95;

-- Changes to table atd_txdot__gndr_lkp
update public.atd_txdot__gndr_lkp set gndr_desc = 'AUTONOMOUS' where gndr_id = 95;

-- Changes to table atd_txdot__injry_sev_lkp
update public.atd_txdot__injry_sev_lkp set injry_sev_desc = 'AUTONOMOUS' where injry_sev_id = 95;

-- Changes to table atd_txdot__inv_da_lkp
insert into public.atd_txdot__inv_da_lkp (inv_da_id, inv_da_desc) values (1662, 'RU');
insert into public.atd_txdot__inv_da_lkp (inv_da_id, inv_da_desc) values (1663, 'T-');
insert into public.atd_txdot__inv_da_lkp (inv_da_id, inv_da_desc) values (1682, 'EO');
insert into public.atd_txdot__inv_da_lkp (inv_da_id, inv_da_desc) values (1702, 'PP');
insert into public.atd_txdot__inv_da_lkp (inv_da_id, inv_da_desc) values (1703, 'T_');

-- Changes to table atd_txdot__occpnt_pos_lkp
update public.atd_txdot__occpnt_pos_lkp set occpnt_pos_desc = 'AUTONOMOUS' where occpnt_pos_id = 95;

-- Changes to table atd_txdot__prsn_type_lkp
update public.atd_txdot__prsn_type_lkp set prsn_type_desc = 'AUTONOMOUS' where prsn_type_id = 95;

-- Changes to table atd_txdot__rpt_autonomous_level_engaged_lkp
insert into public.atd_txdot__rpt_autonomous_level_engaged_lkp (rpt_autonomous_level_engaged_id, rpt_autonomous_level_engaged_desc) values (3, 'CONDITIONAL AUTOMATION');
insert into public.atd_txdot__rpt_autonomous_level_engaged_lkp (rpt_autonomous_level_engaged_id, rpt_autonomous_level_engaged_desc) values (4, 'HIGH AUTOMATION');
insert into public.atd_txdot__rpt_autonomous_level_engaged_lkp (rpt_autonomous_level_engaged_id, rpt_autonomous_level_engaged_desc) values (5, 'FULL AUTOMATION');
update public.atd_txdot__rpt_autonomous_level_engaged_lkp set rpt_autonomous_level_engaged_desc = 'AUTOMATION LEVEL UNKNOWN' where rpt_autonomous_level_engaged_id = 6;

-- Adding table atd_txdot__rpt_road_type_lkp

    create table public.atd_txdot__rpt_road_type_lkp (
        id serial primary key,
        rpt_road_type_id integer not null,
        rpt_road_type_desc varchar(255) not null
    );
    
insert into public.atd_txdot__rpt_road_type_lkp (rpt_road_type_id, rpt_road_type_desc) values (1, 'TWO-WAY, NOT DIVIDED');
insert into public.atd_txdot__rpt_road_type_lkp (rpt_road_type_id, rpt_road_type_desc) values (2, 'TWO-WAY, DIVIDED, UNPROTECTED MEDIAN');
insert into public.atd_txdot__rpt_road_type_lkp (rpt_road_type_id, rpt_road_type_desc) values (3, 'TWO-WAY, DIVIDED, PROTECTED MEDIAN');
insert into public.atd_txdot__rpt_road_type_lkp (rpt_road_type_id, rpt_road_type_desc) values (4, 'ONE WAY');
insert into public.atd_txdot__rpt_road_type_lkp (rpt_road_type_id, rpt_road_type_desc) values (98, 'OTHER (EXPLAIN IN NARRATIVE)');

-- Adding table atd_txdot__trauma_centers_lkp

    create table public.atd_txdot__trauma_centers_lkp (
        id serial primary key,
        trauma_centers_id integer not null,
        trauma_centers_desc varchar(255) not null
    );
    
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (1, 'Abilene Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (2, 'Ballinger Memorial Hospital District');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (3, 'Baptist Hospitals of Southeast Texas');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (4, 'Baptist Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (5, 'Baptist St. Anthonys Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (6, 'Baylor Scott & White All Saints Medical Center - Fort Worth');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (7, 'Baylor Scott & White McLane Childrens Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (8, 'Baylor Scott & White Medical Center - Brenham');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (9, 'Baylor Scott & White Medical Center - College Station');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (10, 'Baylor Scott & White Medical Center - Grapevine');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (11, 'Baylor Scott & White Medical Center - Hillcrest');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (12, 'Baylor Scott & White Medical Center - Lake Pointe');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (13, 'Baylor Scott & White Medical Center - Lakeway');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (14, 'Baylor Scott & White Medical Center - Llano');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (15, 'Baylor Scott & White Medical Center - McKinney');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (16, 'Baylor Scott & White Medical Center - Round Rock');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (17, 'Baylor Scott & White Medical Center - Taylor');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (18, 'Baylor Scott & White Medical Center - Temple');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (19, 'Baylor University Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (20, 'Bayshore Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (21, 'Big Bend Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (22, 'Brownfield Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (23, 'Brownwood Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (24, 'CHI St. Joseph Health Bellville Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (25, 'CHI St. Joseph Health Burleson Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (26, 'CHI St. Joseph Health Grimes Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (27, 'CHI St. Joseph Health Madison Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (28, 'CHI St. Lukes Health - Brazosport');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (29, 'CHI St. Lukes Health - Memorial Livingston');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (30, 'CHI St. Lukes Health Memorial Lufkin');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (31, 'CHRISTUS Good Shepherd Medical Center - Longview');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (32, 'CHRISTUS Good Shepherd Medical Center - Marshall');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (33, 'CHRISTUS Mother Frances Hospital - Jacksonville');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (34, 'CHRISTUS Mother Frances Hospital - Sulphur Springs');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (35, 'CHRISTUS Mother Frances Hospital - Tyler');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (36, 'CHRISTUS Mother Frances Hospital - Winnsboro');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (37, 'CHRISTUS Santa Rosa - Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (38, 'CHRISTUS Santa Rosa Hospital - New Braunfels');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (39, 'CHRISTUS Santa Rosa Hospital - Westover Hills');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (40, 'CHRISTUS Southeast Hospital - St. Elizabeth & St. Mary');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (41, 'CHRISTUS Southeast Texas - Jasper Memorial');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (42, 'CHRISTUS Southeast Texas - St. Mary');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (43, 'CHRISTUS Spohn Hospital Alice');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (44, 'CHRISTUS Spohn Hospital Beeville');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (45, 'CHRISTUS Spohn Hospital Corpus Christi Shoreline');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (46, 'CHRISTUS Spohn Hospital Corpus Christi South');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (47, 'CHRISTUS Spohn Hospital Kleberg');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (48, 'CHRISTUS St. Michael - Atlanta');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (49, 'CHRISTUS St. Michael Health System');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (50, 'Carl R. Darnall Army Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (51, 'Cedar Park Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (52, 'Central Texas Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (53, 'Childrens Hospital of San Antonio');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (54, 'Childrens Medical Center Plano');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (55, 'Childrens Medical Center of Dallas');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (56, 'Childress Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (57, 'Chillicothe Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (58, 'Citizens Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (59, 'Clear Lake Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (60, 'Cogdell Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (61, 'Coleman County Medical Center Company');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (62, 'College Station Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (63, 'Collingsworth General Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (64, 'Columbus Community Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (65, 'Comanche County Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (66, 'Concho County Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (67, 'Connally Memorial Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (68, 'Conroe Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (69, 'Cook Childrens Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (70, 'Coon Memorial Hospital and Home');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (71, 'Coryell Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (72, 'Covenant Childrens Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (73, 'Covenant Hospital Levelland');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (74, 'Covenant Hospital Plainview');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (75, 'Covenant Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (76, 'Cuero Regional Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (77, 'Culberson Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (78, 'Cypress Fairbanks Medical Center Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (79, 'Dallas Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (80, 'Dallas Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (81, 'DeTar Healthcare System');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (82, 'DeTar Healthcare System ***North');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (83, 'Del Sol Medical Center, a campus of LPDS Healthcare');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (84, 'Dell Childrens Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (85, 'Dell Seton Medical Center at The University of Texas');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (86, 'Dimmit Regional Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (87, 'Doctors Hospital at Renaissance');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (88, 'Doctors Hospital of Laredo');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (89, 'Driscoll Childrens Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (90, 'Eastland Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (91, 'Edinburg Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (92, 'El Campo Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (93, 'Electra Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (94, 'Ennis Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (95, 'Faith Community Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (96, 'Fisher County Hospital District');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (97, 'Fort Duncan Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (98, 'Frio Regional Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (99, 'Golden Plains Community Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (100, 'Goodall-Witcher Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (101, 'Graham Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (102, 'Guadalupe Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (103, 'Hamilton General Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (104, 'Hamilton Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (105, 'Hamlin Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (106, 'Hansford County Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (107, 'Hardeman County Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (108, 'Harlingen Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (109, 'Harris Health System Ben Taub Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (110, 'Harris Health System Lyndon B Johnson Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (111, 'Heart Hospital of Austin, a Campus of St. Davids Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (112, 'Heart of Texas Healthcare System');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (113, 'Hemphill County Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (114, 'Hendrick Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (115, 'Hereford Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (116, 'Hill Country Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (117, 'Hill Regional Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (118, 'Houston Northwest Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (119, 'Hunt Regional Medical Center Greenville');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (120, 'Huntsville Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (121, 'Iraan General Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (122, 'Jackson County Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (123, 'John Peter Smith Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (124, 'Kimble Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (125, 'Knapp Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (126, 'Knox County Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (127, 'Lake Granbury Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (128, 'Lamb Healthcare Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (129, 'Laredo Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (130, 'Las Palmas Medical Center, a campus of LPDS Healthcare');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (131, 'Lavaca Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (132, 'Lillian M Hudspeth Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (133, 'Limestone Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (134, 'Longview Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (135, 'Lynn County Hospital District');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (136, 'Mainland Medical Center - a Campus of Clear Lake Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (137, 'Matagorda Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (138, 'McAllen Heart Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (139, 'McAllen Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (140, 'Medical Arts Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (141, 'Medical Center Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (142, 'Medical City Arlington');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (143, 'Medical City Dallas Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (144, 'Medical City Denton');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (145, 'Medical City Lewisville');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (146, 'Medical City McKinney');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (147, 'Medical City North Hills');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (148, 'Medical City Plano');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (149, 'Medical City Weatherford');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (150, 'Medina Regional Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (151, 'Memorial Hermann - Texas Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (152, 'Memorial Hermann Greater Heights Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (153, 'Memorial Hermann Katy Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (154, 'Memorial Hermann Southeast Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (155, 'Memorial Hermann Southwest Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (156, 'Memorial Hermann Sugar Land');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (157, 'Memorial Hermann The Woodlands Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (158, 'Memorial Hospital-***Dumas');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (159, 'Memorial Hospital-***Gonzales');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (160, 'Memorial Hospital-***Seminole');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (161, 'Memorial Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (162, 'Methodist Charlton Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (163, 'Methodist Dallas Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (164, 'Methodist Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (165, 'Methodist Mansfield Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (166, 'Methodist Specialty & Transplant Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (167, 'Methodist Texsan Hospital, a Methodist Hospital Facility');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (168, 'Metroplex Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (169, 'Metropolitan Methodist Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (170, 'Midland Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (171, 'Mission Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (172, 'Mission Trail Baptist Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (173, 'Mitchell County Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (174, 'Muenster Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (175, 'Nacogdoches Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (176, 'Nacogdoches Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (177, 'Navarro Regional Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (178, 'Nix Health Care System');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (179, 'Nocona General Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (180, 'North Austin Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (181, 'North Central Baptist Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (182, 'Northeast Baptist Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (183, 'Northeast Methodist Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (184, 'Northwest Texas Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (185, 'OakBend Medical Center -***JS Main Campus');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (186, 'OakBend Medical Center -***Williams Way Campus');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (187, 'Ochiltree General Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (188, 'Odessa Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (189, 'Otto Kaiser Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (190, 'Palestine Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (191, 'Palo Pinto General Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (192, 'Pampa Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (193, 'Paris Regional Medical Center North Campus');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (194, 'Parkland Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (195, 'Parkview Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (196, 'Parkview Regional Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (197, 'Pecos County Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (198, 'Permian Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (199, 'Plains Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (200, 'Reeves County Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (201, 'Refugio County Memorial Hospital District');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (202, 'Rice Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (203, 'Rio Grande Regional Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (204, 'Rolling Plains Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (205, 'Rollins Brook Community Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (206, 'Round Rock Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (207, 'Sabine County Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (208, 'San Angelo Community Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (209, 'San Antonio Military Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (210, 'Scenic Mountain Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (211, 'Schleicher County Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (212, 'Seton Edgar B. Davis Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (213, 'Seton Highland Lakes Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (214, 'Seton Medical Center Austin');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (215, 'Seton Medical Center Harker Heights');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (216, 'Seton Medical Center Hays');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (217, 'Seton Medical Center Williamson');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (218, 'Seton Northwest Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (219, 'Seton Southwest Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (220, 'Seymour Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (221, 'Shamrock General Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (222, 'Shannon West Texas Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (223, 'Southwest General Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (224, 'St. Davids Georgetown Hospital, a St. Davids Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (225, 'St. Davids Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (226, 'St. Davids South Austin Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (227, 'St. Joseph Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (228, 'St. Joseph Medical Center in the Heights');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (229, 'St. Joseph Regional Health Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (230, 'St. Lukes Baptist Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (231, 'Starr County Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (232, 'Stephens Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (233, 'Stonewall Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (234, 'Sweeny Community Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (235, 'Swisher Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (236, 'TMC Bonham Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (237, 'Texas Childrens Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (238, 'Texas Health Arlington Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (239, 'Texas Health Harris Methodist Alliance');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (240, 'Texas Health Harris Methodist Hospital Azle');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (241, 'Texas Health Harris Methodist Hospital Cleburne');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (242, 'Texas Health Harris Methodist Hospital Fort Worth');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (243, 'Texas Health Harris Methodist Hospital Hurst - Euless  - Bedford');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (244, 'Texas Health Harris Methodist Hospital Stephenville');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (245, 'Texas Health Huguley Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (246, 'Texas Health Presbyterian Hospital Allen');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (247, 'Texas Health Presbyterian Hospital Dallas');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (248, 'Texas Health Presbyterian Hospital Kaufman');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (249, 'Texas Health Presbyterian Hospital Plano');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (250, 'Texoma Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (251, 'The Corpus Christi Medical Center - Bay Area');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (252, 'The Corpus Christi Medical Center - Doctors Regional');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (253, 'The Hospitals of Providence East Campus');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (254, 'The Hospitals of Providence Memorial Campus');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (255, 'The Hospitals of Providence Sierra Campus');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (256, 'The Hospitals of Providence Transmountain Campus');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (257, 'The Medical Center of Southeast Texas');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (258, 'The Womans Hospital of Texas');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (259, 'Throckmorton County Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (260, 'Titus Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (261, 'Tomball Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (262, 'Tyler County Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (263, 'UT Health East Texas Athens Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (264, 'UT Health East Texas Carthage Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (265, 'UT Health East Texas Henderson Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (266, 'UT Health East Texas Jacksonville Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (267, 'UT Health East Texas Pittsburg Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (268, 'UT Health East Texas Quitman Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (269, 'UT Health East Texas Tyler Regional Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (270, 'UTMB Health Angleton Danbury Campus');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (271, 'United Memorial Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (272, 'United Regional Health Care System');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (273, 'University Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (274, 'University Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (275, 'University Medical Center of El Paso');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (276, 'University of Texas Health Center at Tyler');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (277, 'University of Texas Medical Branch');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (278, 'Uvalde Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (279, 'Val Verde Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (280, 'Valley Baptist Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (281, 'Valley Baptist Medical Center - Brownsville');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (282, 'Valley Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (283, 'W.J. Mangold Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (284, 'Wadley Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (285, 'Ward Memorial Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (286, 'West Houston Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (287, 'Wilbarger General Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (288, 'William Beaumont Army Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (289, 'Wilson N. Jones Regional Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (290, 'Wise Health System');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (291, 'Woodland Heights Medical Center');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (292, 'Yoakum Community Hospital');
insert into public.atd_txdot__trauma_centers_lkp (trauma_centers_id, trauma_centers_desc) values (293, 'Yoakum County Hospital');

-- Changes to table atd_txdot__unit_dfct_lkp
insert into public.atd_txdot__unit_dfct_lkp (unit_dfct_id, unit_dfct_desc) values (10, 'AUTOMATION FAILURE');

-- Changes to table atd_txdot__veh_body_styl_lkp
insert into public.atd_txdot__veh_body_styl_lkp (veh_body_styl_id, veh_body_styl_desc) values (109, 'SCHOOL BUS OTHER');

-- Changes to table atd_txdot__veh_make_lkp
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (794, 'ALEXANDER DENNIS');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (795, 'ARCTIC CAT');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (796, 'AUTOMOBILI PININFARINA');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (797, 'BRIGHTDROP');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (799, 'CHE');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (800, 'CRUISE');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (801, 'DENNIS EAGLE');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (802, 'ELECTRA MECCANICA VEHICLES CORPORATION');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (803, 'ENERGICA');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (805, 'FISKER INC.');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (808, 'GREENPOWER MOTORS');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (809, 'IRIZAR');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (811, 'LION');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (812, 'LIVEWIRE');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (813, 'LORDSTOWN EV CORPORATION');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (815, 'ORANGE EV');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (817, 'ROKON');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (818, 'TOY');
insert into public.atd_txdot__veh_make_lkp (veh_make_id, veh_make_desc) values (819, 'VINFAST TRADING AND PRODUCTION LLC');

-- Changes to table atd_txdot__veh_mod_lkp
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5795, 'ENVIRO 200');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5796, 'ENVIRO 400');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5797, 'ENVIRO 500');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5798, 'ENVIRO 500 SUPERFLO');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5799, 'ENVIRO 500EV');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5800, 'TONALE');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5801, 'TUAREG');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5802, 'TUONO V4');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5803, 'ALTERRA');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5804, 'PROWLER');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5805, 'PROWLER PRO');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5806, 'WILDCAT XX');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5807, 'E-TRON S');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5808, 'Q4 E-TRON');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5809, 'Q8 E-TRON');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5810, 'BATTISTA');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5811, 'CE 04');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5812, 'F 750');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5813, 'F 850');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5814, 'F 900');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5815, 'I4 EDRIVE35');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5816, 'I4 EDRIVE40');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5817, 'I4 M50');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5818, 'I7');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5819, 'IX');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5820, 'R 1250');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5821, 'XM');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5822, 'EV600');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5823, 'ZEVO 600');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5824, 'ESCALADE V');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5825, 'LYRIQ');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5826, 'P');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5827, '7500XD');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5828, 'SILVERADO LTD');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5829, 'AG');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5830, 'CRUISE AV');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5831, 'ELITE NAS1');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5832, 'HORNET');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5833, 'DESERT X');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5836, 'SOLO');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5837, 'EGO');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5838, 'EVA');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5839, 'EVA ESSEESSE9');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5840, 'EVA RIBELLE');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5841, 'EXPERIA');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5842, 'FIRE APPARATUS');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5843, '296GTB');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5844, '812 COMPETIZIONE');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5845, 'PORTOFINO M');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5846, 'SF 90 SPIDER');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5847, 'OCEAN');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5849, 'ECASCADIA 116');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5850, 'GV60');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5851, 'HUMMER');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5852, 'EV250');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5853, 'EV350');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5854, 'EVC210');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5855, 'EVS300');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5857, 'FLHCSANV');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5859, 'FLHTCUTGANV');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5860, 'FLHTKANV');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5861, 'FLHXSANV');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5862, 'FLHXST');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5863, 'FLTRKSE');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5864, 'FLTRT');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5865, 'FLTRXSANV');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5866, 'FLTRXSEANV');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5867, 'FLTRXST');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5868, 'FLXRS');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5869, 'FLXRST');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5870, 'FXRST');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5871, 'RH975');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5872, 'S41/S42');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5873, 'NVA110');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5878, 'XR150L');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5879, 'EE 5');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5880, 'FC 350');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5881, 'FS 450');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5882, 'FX 350');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5883, 'FX 450');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5884, 'NORDEN 901');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5885, 'SUPERMOTO 701');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5886, 'TC 50');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5887, 'TE 150I');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5888, 'TE 300I');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5889, 'TX 300');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5890, 'VITPILEN 401/SVARTPILEN 401');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5891, 'KONA N');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5892, 'PURSUIT');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5894, 'MV60E');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5895, 'GAMA I6');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5896, 'KRF 1000');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5897, 'KRT1000');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5898, 'KX112');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5900, 'ZX400');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5901, 'EV6');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5903, '144');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5905, 'LION 8');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5906, 'LION C V1');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5907, 'LION C V2');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5908, 'LION M');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5909, 'LION6');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5910, 'LW1');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5911, 'ENDURANCE');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5912, 'DRAGSTER');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5913, 'SUPERVELOCE');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5914, 'GRECALE');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5915, 'CX-50');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5916, 'CX-90');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5917, '765LT');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5918, 'ARTURA');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5919, 'ELVA');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5920, 'EQB');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5921, 'EQE');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5922, 'EQS');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5923, 'V85 TT');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5924, 'D4020/D4520');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5925, 'D40CRT/D45CRT');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5926, 'J3500/J4500');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5927, 'ARIYA');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5929, 'Z');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5930, 'TERMINAL TRACTOR');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5931, '536');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5932, '537');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5933, '548');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5934, 'EDV');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5935, 'R1S');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5936, 'TRAIL-BREAKER');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5939, 'SOLTERRA');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5940, 'DL800DE');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5941, 'GSX1000');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5942, 'GSX800');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5943, 'LT-F400');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5944, 'D');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5945, 'BZ4X');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5946, 'COROLLA CROSS');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5947, 'GR 86');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5948, 'GR COROLLA');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5949, 'VF 8');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5950, 'VF 9');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5952, 'C40');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5954, '47X CHASSIS');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5955, '49X CHASSIS');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5956, '57X CHASSIS');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5957, 'NEW 4700 CHASSIS');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5958, 'NEW 57X CHASSIS');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5959, 'SA01');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5960, 'MT-03');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5961, 'MTM690');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5962, 'MTM890');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5963, 'MTN1000');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5964, 'XTZ690');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5965, '13 SERIES');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5966, '7 SERIES');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5967, '8 SERIES');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5968, '9 SERIES');
insert into public.atd_txdot__veh_mod_lkp (veh_mod_id, veh_mod_desc) values (5969, 'FXE');
