delete from lookups.agency where id = 10013;
delete from lookups.agency where id = 10228;
delete from lookups.agency where id = 10229;
delete from lookups.agency where id = 10231;
delete from lookups.agency where id = 10232;
delete from lookups.agency where id = 3355;
delete from lookups.agency where id = 3356;
delete from lookups.agency where id = 3357;
delete from lookups.agency where id = 3359;
delete from lookups.agency where id = 3360;
delete from lookups.agency where id = 3361;
delete from lookups.agency where id = 3362;
delete from lookups.agency where id = 3363;
delete from lookups.agency where id = 3364;
insert into lookups.agency (id, label, source) values (1167, 'DALLAS CITY MARSHAL''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (1201, 'DIBOLL ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1226, 'EAGLE PASS ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1278, 'ESTELLINE POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1326, 'FREESTONE COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (1441, 'HENDERSON COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (151, 'BRAZOS COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (1520, 'ITASCA POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1666, 'LIBERTY EYLAU ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (167, 'BROWN COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (1684, 'LOCKNEY POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1723, 'MALONE POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1765, 'MEDINA COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (1802, 'MOORE COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (1822, 'NORTH FOREST ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1832, 'NAVARRO COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (1894, 'PALACIOS ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1930, 'PINE FOREST POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1956, 'PORT OF HOUSTON AUTHORITY POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1968, 'PRESIDIO ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (1983, 'RANDALL COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (2070, 'SAN ANTONIO PARK POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (2092, 'SANTA ROSA ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (212, 'CARRIZO SPRINGS CISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (220, 'CASTRO COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (2202, 'SWEENY ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (2272, 'THORNTON POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (2296, 'TRINITY COUNTY CONSTABLE PRECINCT 3', 'cris');
insert into lookups.agency (id, label, source) values (2314, 'TYLER ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (2320, 'UNIVERSITY OF MARY HARDIN BAYLOR POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (234, 'CHAMBERS COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (23673, 'BURLINGTON NORTHERN SANTA FE RAILROAD COMPANY POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (23682, 'COMAL COUNTY CONSTABLE’S OFFICE PCT 4', 'cris');
insert into lookups.agency (id, label, source) values (23773, 'TRAVIS COUNTY - AUSTIN EMS', 'cris');
insert into lookups.agency (id, label, source) values (23794, 'ANGELINA COLLEGE POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (23816, 'COLEMAN COUNTY SHERIFF’S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (23845, 'COPPER CANYON POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (23846, 'WILSON COUNTY CONSTABLE OFFICE PRECINCT 3', 'cris');
insert into lookups.agency (id, label, source) values (23854, 'JEFFERSON COUNTY SHERIFF’S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (23897, 'SWISHER COUNTY SHERIFF’S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (24043, 'AUSTIN COMMUNITY COLLEGE DISTRICT POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (2446, 'WINONA POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (2461, 'YOAKUM COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (2586, 'CHEROKEE COUNTY CONSTABLE PRECINCT 3', 'cris');
insert into lookups.agency (id, label, source) values (2590, 'COCHRAN COUNTY CONSTABLE PRECINCT 1', 'cris');
insert into lookups.agency (id, label, source) values (2602, 'COMAL COUNTY CONSTABLE PRECINCT 2', 'cris');
insert into lookups.agency (id, label, source) values (262, 'LEFORS CITY MARSHAL''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (275, 'STAR HARBOR POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (2779, 'HOUSTON COUNTY CONSTABLE PRECINCT 2', 'cris');
insert into lookups.agency (id, label, source) values (2831, 'KENDALL COUNTY CONSTABLE PRECINCT 4', 'cris');
insert into lookups.agency (id, label, source) values (2839, 'KLEBERG COUNTY CONSTABLE PRECINCT 1', 'cris');
insert into lookups.agency (id, label, source) values (2871, 'LIBERTY COUNTY CONSTABLE PRECINCT 3', 'cris');
insert into lookups.agency (id, label, source) values (2872, 'LIBERTY COUNTY CONSTABLE PRECINCT 4', 'cris');
insert into lookups.agency (id, label, source) values (2887, 'LUBBOCK COUNTY CONSTABLE PRECINCT 3', 'cris');
insert into lookups.agency (id, label, source) values (3078, 'TRINITY COUNTY CONSTABLE PRECINCT 1', 'cris');
insert into lookups.agency (id, label, source) values (3123, 'WEBB COUNTY CONSTABLE PRECINCT 3', 'cris');
insert into lookups.agency (id, label, source) values (3168, 'LAREDO AIRPORT POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3171, 'PANOLA COLLEGE POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3173, 'VINTON POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3174, 'WHITE RIVER WATER DISTRICT POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3181, 'HUGHES SPRINGS ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3183, 'WAYLAND BAPTIST UNIVERSITY POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3186, 'SAN ANGELO REGIONAL AIRPORT POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (321, 'CONCORDIA UNIVERSITY POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3250, 'UNIVERSITY OF NORTH TEXAS AT DALLAS POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3254, 'HOWE ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3257, 'ELLIS COUNTY CONSTABLE PRECINCT 3', 'cris');
insert into lookups.agency (id, label, source) values (3258, 'DALLAS COUNTY CONSTABLE PRECINCT 2', 'cris');
insert into lookups.agency (id, label, source) values (3262, 'KAUFMAN COUNTY CONSTABLE PRECINCT 2', 'cris');
insert into lookups.agency (id, label, source) values (3264, 'OLDHAM COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (3270, 'DODD CITY ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3273, 'LONDON ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3275, 'SEYMOUR ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3281, 'PECOS BARSTOW TOYAH ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3283, 'FREER INDEPENDENT SCHOOL DISTRICT POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3284, 'SANDY OAKS MARSHAL''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (3287, 'WALKER COUNTY CONSTABLE PRECINCT 3', 'cris');
insert into lookups.agency (id, label, source) values (3290, 'MCMULLEN COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (3291, 'CAMERON COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (3295, 'WASHINGTON COUNTY CONSTABLE PCT. 1', 'cris');
insert into lookups.agency (id, label, source) values (3299, 'JEFFERSON COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.agency (id, label, source) values (3310, 'WASHINGTON COUNTY CONSTABLE OFFICE PRECINCT 2', 'cris');
insert into lookups.agency (id, label, source) values (3313, 'CENTER POINT ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3314, 'SULPHUR SPRINGS ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3323, 'POLK COUNTY CONSTABLE PRECINCT 1', 'cris');
insert into lookups.agency (id, label, source) values (3335, 'IDALOU ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (42, 'ANGELINA COLLEGE POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (71, 'AUSTIN COLLEGE POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (795, 'FALLS COUNTY CONSTABLE PRECINCT 3', 'cris');
update lookups.agency set label = 'TEXAS WOMAN''S UNIVERSITY DEPARTMENT OF PUBLIC SAFETY' where id = 2264;
update lookups.agency set label = 'TRAVIS COUNTY-TNR-TE' where id = 10170;
