services:
  import:
    build: .
    volumes:
      - .:/app
    env_file:
      - ./.env
    volumes:
      # mount local COACD network directory to container
      - /mnt/vision_zero_cad:/mnt/vision_zero_cad
