CREATE TABLE cad_incidents (
    id serial PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    created_by text DEFAULT 'system'::text NOT NULL,
    updated_by text DEFAULT 'system'::text NOT NULL,
    address text,
    agency_type text,
    call_disposition text,
    final_problem text,
    incident_type text,
    initial_problem text,
    master_incident_id integer UNIQUE,
    master_incident_number text,
    priority_description text,
    priority_number integer,
    response_date TIMESTAMP WITH TIME ZONE,
    time_call_closed TIMESTAMP WITH TIME ZONE,
    time_first_unit_arrived TIMESTAMP WITH TIME ZONE,
    latitude numeric,
    longitude numeric,
    geom geometry (POINT, 4326),
    location_id text,
    in_austin_full_purpose boolean
);

ALTER TABLE cad_incidents
ADD CONSTRAINT cad_incidents_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations (location_id) ON UPDATE CASCADE ON DELETE SET NULL;

CREATE TRIGGER set_updated_at_timestamp_cad_incidents BEFORE
UPDATE ON public.cad_incidents FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_timestamp ();

CREATE INDEX idx_cad_incidents_geom ON cad_incidents USING GIST (geom);

CREATE INDEX idx_cad_incidents_response_date ON cad_incidents (response_date);

comment ON TABLE cad_incidents IS 'This dataset contains information on both 911 calls (usually referred to as Calls for Service or Dispatched Incidents) and officer-initiated incidents related to traffic crashes as recorded in the Austin public safety Computer Aided Dispatch (CAD) system. Data is provided by the public safety enterprise data team after approval by AFD, ATCEMS, and APD';

comment ON COLUMN cad_incidents.id IS 'Serial primary key generated by the Vision Zero database';

comment ON COLUMN cad_incidents.created_at IS 'The date the record was created in the Vision Zero database';

comment ON COLUMN cad_incidents.updated_at IS 'The date the record was last updated in the Vision Zero database - set via trigger';

comment ON COLUMN cad_incidents.created_by IS 'The name of the user who created the record in the Vision Zero database';

comment ON COLUMN cad_incidents.updated_by IS 'The name of the user who last updated the record in the Vision Zero database';

comment ON COLUMN cad_incidents.address IS 'The address of the incident location';

comment ON COLUMN cad_incidents.agency_type IS 'The agency responding to the incident. Either "AUSTIN PD", "AUSTIN-TRAVIS COUNTY  EMS", or "FIRE"';

comment ON COLUMN cad_incidents.call_disposition IS 'A description of the outcome of the incident';

comment ON COLUMN cad_incidents.final_problem IS 'A description of the ultimate issue that was meant to be addressed by the CAD incident. This may differ from the initial problem description based on additional information that comes to light during the call-taking and response processes';

comment ON COLUMN cad_incidents.incident_type IS 'A categorization of type of incident response needed';

comment ON COLUMN cad_incidents.initial_problem IS 'A preliminary description of the problem meant to be addressed by the CAD incident based on either the information given to the 911 call taker in the case of dispatched incidents, or information collected by officers in the case of officer-initiated incidents. Initial problem descriptions may differ from final problem descriptions based on additional information that comes to light during the call-taking and response processes';

comment ON COLUMN cad_incidents.master_incident_id IS 'A serial integer column that serves as the CAD database primary key';

comment ON COLUMN cad_incidents.master_incident_number IS 'An unique integer or string identifying a computer-aided dispatch incident - format varies by agency. This number is used as an incident-level primary key by agencies. In APD, it is the so-called "Case ID" that can be found in TxDOT crash reports and within the Brazos system and can be used to join records accordingly. EMS and AFD incident records can also be joined on this column.';

comment ON COLUMN cad_incidents.priority_description IS 'A description of the priority level assigned to the incident at the time of the first unit arrival';

comment ON COLUMN cad_incidents.priority_number IS 'The priority level assigned to the incident at the time of the first unit arrival. Generally, lower numbers indicate higher priority (zero being the highest) but usage varies across agencies';

comment ON COLUMN cad_incidents.response_date IS 'The date and time that the 911 call-takers Emergency Call Taker (ECT) screen opened following the 911 call being answered in the case of dispatched incidents. In the case of officer-initiated incidents, this field indicates the time the incident was created and sent to the incident queue if it was created via the officer''s onboard computer or the time the dispatcher opened their ECT screen and created the incident if the officer created the incident through dispatch.';

comment ON COLUMN cad_incidents.time_call_closed IS 'The date and time that the incident was closed, indicating that all units have left the scene and it is no longer active.';

comment ON COLUMN cad_incidents.time_first_unit_arrived IS 'The date and time that the first responding unit arrived on scene to the incident. This is the endpoint for response time calculations. Multiple units may arrive on a single incident, while individual units may be made up of one or more responders.';

comment ON COLUMN cad_incidents.latitude IS 'The incident location latitude in decimal degrees';

comment ON COLUMN cad_incidents.longitude IS 'The incident location longitude in decimal degrees';

comment ON COLUMN cad_incidents.geom IS 'Geometry point column set via trigger based on the record''s latitude and longitude values';

comment ON COLUMN cad_incidents.location_id IS 'The location polygon that intersects with this record''s geometry — set via trigger';

comment ON COLUMN cad_incidents.in_austin_full_purpose IS 'Boolean column indicating if this record''s point geometry falls within the Austin Full Purpose jurisdiction - set via trigger';

CREATE
OR REPLACE FUNCTION cad_incidents_set_spatial_attributes () RETURNS trigger AS $$
DECLARE
    v_location_id text;
BEGIN
    --
    -- Create geometry
    --
    NEW.geom := ST_SetSRID(
        ST_MakePoint(NEW.longitude, NEW.latitude),
        4326
    );
    --
    -- Set location_id
    --
    -- Find location_id with group priority (1 first, then 2)
    SELECT location_id INTO v_location_id
    FROM locations
    WHERE location_group = 1 
        AND NEW.geom && geometry 
        AND ST_Contains(geometry, NEW.geom)
        AND is_deleted = FALSE
    LIMIT 1;
    -- If no group 1 location found, try group 2
    IF v_location_id IS NULL THEN
        SELECT location_id INTO v_location_id
        FROM locations
        WHERE location_group = 2 
            AND NEW.geom && geometry 
            AND ST_Contains(geometry, NEW.geom)
            AND is_deleted = FALSE
        LIMIT 1;
    END IF;
    NEW.location_id = v_location_id;
    --
    -- Set in_austin_full_purpose
    --    
    NEW.in_austin_full_purpose = EXISTS (
        SELECT
            1
        FROM
            geo.jurisdictions
        WHERE
            JURISDICTION_LABEL = 'AUSTIN FULL PURPOSE'
            AND ST_Intersects (geometry, NEW.geom)
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE
OR REPLACE TRIGGER trigger_cad_incidents_set_spatial_attributes BEFORE INSERT
OR
UPDATE OF latitude,
longitude ON cad_incidents FOR EACH ROW
EXECUTE FUNCTION cad_incidents_set_spatial_attributes ();