create table db.people_cris (
    id serial primary key,
    crash_id integer references db.crashes_cris (crash_id) on delete cascade on update cascade,
    drvr_city_name text,
    drvr_drg_cat_1_id integer references lookups.substnc_cat_lkp (id) on update cascade on delete cascade,
    drvr_zip text,
    is_primary_person boolean,
    prsn_age integer,
    prsn_alc_rslt_id integer references lookups.substnc_tst_result_lkp (id) on update cascade on delete cascade,
    prsn_alc_spec_type_id integer references lookups.specimen_type_lkp (id) on update cascade on delete cascade,
    prsn_bac_test_rslt text,
    prsn_death_date timestamptz,
    prsn_death_time timestamptz,
    prsn_drg_rslt_id integer references lookups.substnc_tst_result_lkp (id) on update cascade on delete cascade,
    prsn_drg_spec_type_id integer references lookups.specimen_type_lkp (id) on update cascade on delete cascade,
    prsn_ethnicity_id integer references lookups.drvr_ethncty_lkp (id) on update cascade on delete cascade,
    prsn_first_name text,
    prsn_gndr_id integer references lookups.gndr_lkp (id) on update cascade on delete cascade,
    prsn_helmet_id integer references lookups.helmet_lkp (id) on update cascade on delete cascade,
    prsn_injry_sev_id integer references lookups.injry_sev_lkp (id) on update cascade on delete cascade,
    prsn_last_name text,
    prsn_mid_name text,
    prsn_name_sfx text,
    prsn_nbr integer,
    prsn_occpnt_pos_id integer references lookups.occpnt_pos_lkp (id) on update cascade on delete cascade,
    prsn_rest_id integer references lookups.rest_lkp (id) on update cascade on delete cascade,
    prsn_taken_by text,
    prsn_taken_to text,
    prsn_type_id integer references lookups.prsn_type_lkp (id) on update cascade on delete cascade,
    unit_id integer not null references db.units_cris (id) on update cascade on delete cascade,
    unit_nbr integer
);

create table db.people_edits (
    id integer primary key references db.people_cris (id) on update cascade on delete cascade,
    apd_annual_fatality_number integer,
    drvr_city_name text,
    drvr_drg_cat_1_id integer references lookups.substnc_cat_lkp (id) on update cascade on delete cascade,
    drvr_zip text,
    ems_id integer references public.ems__incidents (id) on update cascade on delete set null,
    is_primary_person boolean,
    prsn_age integer,
    prsn_alc_rslt_id integer references lookups.substnc_tst_result_lkp (id) on update cascade on delete cascade,
    prsn_alc_spec_type_id integer references lookups.specimen_type_lkp (id) on update cascade on delete cascade,
    prsn_bac_test_rslt text,
    prsn_death_date timestamptz,
    prsn_death_time timestamptz,
    prsn_drg_rslt_id integer references lookups.substnc_tst_result_lkp (id) on update cascade on delete cascade,
    prsn_drg_spec_type_id integer references lookups.specimen_type_lkp (id) on update cascade on delete cascade,
    prsn_ethnicity_id integer references lookups.drvr_ethncty_lkp (id) on update cascade on delete cascade,
    prsn_first_name text,
    prsn_gndr_id integer references lookups.gndr_lkp (id) on update cascade on delete cascade,
    prsn_helmet_id integer references lookups.helmet_lkp (id) on update cascade on delete cascade,
    prsn_injry_sev_id integer references lookups.injry_sev_lkp (id) on update cascade on delete cascade,
    prsn_last_name text,
    prsn_mid_name text,
    prsn_name_sfx text,
    prsn_nbr integer,
    prsn_occpnt_pos_id integer references lookups.occpnt_pos_lkp (id) on update cascade on delete cascade,
    prsn_rest_id integer references lookups.rest_lkp (id) on update cascade on delete cascade,
    prsn_taken_by text,
    prsn_taken_to text,
    prsn_type_id integer references lookups.prsn_type_lkp (id) on update cascade on delete cascade,
    unit_id integer references db.units_cris (id) on update cascade on delete cascade
);

create table db.people_unified (
    id integer primary key,
    apd_annual_fatality_number integer,
    drvr_city_name text,
    drvr_drg_cat_1_id integer references lookups.substnc_cat_lkp (id) on update cascade on delete cascade,
    drvr_zip text,
    ems_id integer references public.ems__incidents (id) on update cascade on delete set null,
    is_primary_person boolean,
    prsn_age integer,
    prsn_alc_rslt_id integer references lookups.substnc_tst_result_lkp (id) on update cascade on delete cascade,
    prsn_alc_spec_type_id integer references lookups.specimen_type_lkp (id) on update cascade on delete cascade,
    prsn_bac_test_rslt text,
    prsn_death_date timestamptz,
    prsn_death_time timestamptz,
    prsn_drg_rslt_id integer references lookups.substnc_tst_result_lkp (id) on update cascade on delete cascade,
    prsn_drg_spec_type_id integer references lookups.specimen_type_lkp (id) on update cascade on delete cascade,
    prsn_ethnicity_id integer references lookups.drvr_ethncty_lkp (id) on update cascade on delete cascade,
    prsn_first_name text,
    prsn_gndr_id integer references lookups.gndr_lkp (id) on update cascade on delete cascade,
    prsn_helmet_id integer references lookups.helmet_lkp (id) on update cascade on delete cascade,
    prsn_injry_sev_id integer references lookups.injry_sev_lkp (id) on update cascade on delete cascade,
    prsn_last_name text,
    prsn_mid_name text,
    prsn_name_sfx text,
    prsn_nbr integer,
    prsn_occpnt_pos_id integer references lookups.occpnt_pos_lkp (id) on update cascade on delete cascade,
    prsn_rest_id integer references lookups.rest_lkp (id) on update cascade on delete cascade,
    prsn_taken_by text,
    prsn_taken_to text,
    prsn_type_id integer references lookups.prsn_type_lkp (id) on update cascade on delete cascade,
    unit_id integer not null references db.units_unified (id) on update cascade on delete cascade,
    years_of_life_lost integer generated always as (case when prsn_injry_sev_id = 4 then greatest(75 - prsn_age, 0) else 0 end) stored
);
