create table db.crashes_cris (
    crash_id integer primary key,
    active_school_zone_fl boolean,
    at_intrsct_fl boolean,
    case_id text,
    crash_date timestamp with time zone,
    crash_speed_limit integer,
    crash_time timestamp with time zone,
    fhe_collsn_id integer references lookups.collsn_lkp (id) on update cascade on delete cascade,
    intrsct_relat_id integer references lookups.intrsct_relat_lkp (id) on update cascade on delete cascade,
    investigat_agency_id integer references lookups.agency_lkp (id) on update cascade on delete cascade,
    investigator_narrative text,
    latitude numeric,
    light_cond_id integer references lookups.light_cond_lkp (id) on update cascade on delete cascade,
    longitude numeric,
    medical_advisory_fl boolean,
    obj_struck_id integer references lookups.obj_struck_lkp (id) on update cascade on delete cascade,
    onsys_fl boolean,
    private_dr_fl boolean,
    road_constr_zone_fl boolean,
    road_constr_zone_wrkr_fl boolean,
    rpt_block_num text,
    rpt_city_id integer references lookups.city_lkp (id) on update cascade on delete cascade,
    rpt_cris_cnty_id integer references lookups.cnty_lkp (id) on update cascade on delete cascade,
    rpt_hwy_num text,
    rpt_rdwy_sys_id integer references lookups.rwy_sys_lkp (id) on update cascade on delete cascade,
    rpt_ref_mark_dir text,
    rpt_ref_mark_dist_uom text,
    rpt_ref_mark_offset_amt numeric,
    rpt_road_part_id integer references lookups.road_part_lkp (id) on update cascade on delete cascade,
    rpt_sec_block_num text,
    rpt_sec_hwy_num text,
    rpt_sec_rdwy_sys_id integer references lookups.rwy_sys_lkp (id) on update cascade on delete cascade,
    rpt_sec_road_part_id integer references lookups.road_part_lkp (id) on update cascade on delete cascade,
    rpt_sec_street_desc text,
    rpt_sec_street_name text,
    rpt_sec_street_pfx text,
    rpt_sec_street_sfx text,
    rpt_street_desc text,
    rpt_street_name text,
    rpt_street_pfx text,
    rpt_street_sfx text,
    rr_relat_fl boolean,
    schl_bus_fl boolean,
    surf_cond_id integer references lookups.surf_cond_lkp (id) on update cascade on delete cascade,
    surf_type_id integer references lookups.surf_type_lkp (id) on update cascade on delete cascade,
    thousand_damage_fl boolean,
    toll_road_fl boolean,
    traffic_cntl_id integer references lookups.traffic_cntl_lkp (id) on update cascade on delete cascade,
    txdot_rptable_fl boolean,
    wthr_cond_id integer references lookups.wthr_cond_lkp (id) on update cascade on delete cascade
);

create table db.crashes_edits (
    crash_id integer primary key references db.crashes_cris (crash_id) on update cascade on delete cascade,
    active_school_zone_fl boolean,
    at_intrsct_fl boolean,
    case_id text,
    crash_date timestamp with time zone,
    crash_speed_limit integer,
    crash_time timestamp with time zone,
    fhe_collsn_id integer references lookups.collsn_lkp (id) on update cascade on delete cascade,
    intrsct_relat_id integer references lookups.intrsct_relat_lkp (id) on update cascade on delete cascade,
    investigat_agency_id integer references lookups.agency_lkp (id) on update cascade on delete cascade,
    investigator_narrative text,
    latitude numeric,
    light_cond_id integer references lookups.light_cond_lkp (id) on update cascade on delete cascade,
    longitude numeric,
    medical_advisory_fl boolean,
    obj_struck_id integer references lookups.obj_struck_lkp (id) on update cascade on delete cascade,
    onsys_fl boolean,
    private_dr_fl boolean,
    road_constr_zone_fl boolean,
    road_constr_zone_wrkr_fl boolean,
    rpt_block_num text,
    rpt_city_id integer references lookups.city_lkp (id) on update cascade on delete cascade,
    rpt_cris_cnty_id integer references lookups.cnty_lkp (id) on update cascade on delete cascade,
    rpt_hwy_num text,
    rpt_rdwy_sys_id integer references lookups.rwy_sys_lkp (id) on update cascade on delete cascade,
    rpt_ref_mark_dir text,
    rpt_ref_mark_dist_uom text,
    rpt_ref_mark_offset_amt numeric,
    rpt_road_part_id integer references lookups.road_part_lkp (id) on update cascade on delete cascade,
    rpt_sec_block_num text,
    rpt_sec_hwy_num text,
    rpt_sec_rdwy_sys_id integer references lookups.rwy_sys_lkp (id) on update cascade on delete cascade,
    rpt_sec_road_part_id integer references lookups.road_part_lkp (id) on update cascade on delete cascade,
    rpt_sec_street_desc text,
    rpt_sec_street_name text,
    rpt_sec_street_pfx text,
    rpt_sec_street_sfx text,
    rpt_street_desc text,
    rpt_street_name text,
    rpt_street_pfx text,
    rpt_street_sfx text,
    rr_relat_fl boolean,
    schl_bus_fl boolean,
    surf_cond_id integer references lookups.surf_cond_lkp (id) on update cascade on delete cascade,
    surf_type_id integer references lookups.surf_type_lkp (id) on update cascade on delete cascade,
    thousand_damage_fl boolean,
    toll_road_fl boolean,
    traffic_cntl_id integer references lookups.traffic_cntl_lkp (id) on update cascade on delete cascade,
    txdot_rptable_fl boolean,
    wthr_cond_id integer references lookups.wthr_cond_lkp (id) on update cascade on delete cascade
);

create table db.crashes_unified (
    crash_id integer primary key references db.crashes_cris (crash_id) on update cascade on delete cascade,
    active_school_zone_fl boolean,
    address_primary text generated always as (trim(coalesce(rpt_street_pfx, '') || ' ' || coalesce(rpt_block_num, '') || ' ' || coalesce(rpt_street_name, '') || ' ' || coalesce(rpt_street_sfx, ''))) stored,
    address_secondary text generated always as (trim(coalesce(rpt_sec_street_pfx, '') || ' ' || coalesce(rpt_sec_block_num, '') || ' ' || coalesce(rpt_sec_street_name, '') || ' ' || coalesce(rpt_sec_street_sfx, ''))) stored,
    at_intrsct_fl boolean,
    case_id text,
    council_district integer,
    cr3_file_metadata jsonb,
    cr3_ocr_extraction_date timestamp with time zone,
    cr3_stored_flag boolean,
    crash_date timestamp with time zone,
    crash_speed_limit integer,
    crash_time timestamp with time zone,
    fhe_collsn_id integer references lookups.collsn_lkp (id) on update cascade on delete cascade,
    in_austin_full_purpose boolean,
    intrsct_relat_id integer references lookups.intrsct_relat_lkp (id) on update cascade on delete cascade,
    investigat_agency_id integer references lookups.agency_lkp (id) on update cascade on delete cascade,
    investigator_narrative text,
    investigator_narrative_ocr text,
    latitude numeric,
    light_cond_id integer references lookups.light_cond_lkp (id) on update cascade on delete cascade,
    location_id text references public.atd_txdot_locations (location_id) on update cascade on delete set null,
    longitude numeric,
    medical_advisory_fl boolean,
    obj_struck_id integer references lookups.obj_struck_lkp (id) on update cascade on delete cascade,
    onsys_fl boolean,
    position geometry(Point, 4326),
    private_dr_fl boolean,
    road_constr_zone_fl boolean,
    road_constr_zone_wrkr_fl boolean,
    rpt_block_num text,
    rpt_city_id integer references lookups.city_lkp (id) on update cascade on delete cascade,
    rpt_cris_cnty_id integer references lookups.cnty_lkp (id) on update cascade on delete cascade,
    rpt_hwy_num text,
    rpt_rdwy_sys_id integer references lookups.rwy_sys_lkp (id) on update cascade on delete cascade,
    rpt_ref_mark_dir text,
    rpt_ref_mark_dist_uom text,
    rpt_ref_mark_offset_amt numeric,
    rpt_road_part_id integer references lookups.road_part_lkp (id) on update cascade on delete cascade,
    rpt_sec_block_num text,
    rpt_sec_hwy_num text,
    rpt_sec_rdwy_sys_id integer references lookups.rwy_sys_lkp (id) on update cascade on delete cascade,
    rpt_sec_road_part_id integer references lookups.road_part_lkp (id) on update cascade on delete cascade,
    rpt_sec_street_desc text,
    rpt_sec_street_name text,
    rpt_sec_street_pfx text,
    rpt_sec_street_sfx text,
    rpt_street_desc text,
    rpt_street_name text,
    rpt_street_pfx text,
    rpt_street_sfx text,
    rr_relat_fl boolean,
    schl_bus_fl boolean,
    surf_cond_id integer references lookups.surf_cond_lkp (id) on update cascade on delete cascade,
    surf_type_id integer references lookups.surf_type_lkp (id) on update cascade on delete cascade,
    thousand_damage_fl boolean,
    toll_road_fl boolean,
    traffic_cntl_id integer references lookups.traffic_cntl_lkp (id) on update cascade on delete cascade,
    txdot_rptable_fl boolean,
    wthr_cond_id integer references lookups.wthr_cond_lkp (id) on update cascade on delete cascade
);
