drop trigger if exists crash_insert_ems_match_trigger on crashes;
drop trigger if exists crash_update_ems_match_trigger on crashes;
alter table ems__incidents drop column apd_case_ids;
alter table ems__incidents rename column crash_pk to crash_id;
alter table ems__incidents drop column match_status;
alter table ems__incidents drop column patient_injry_sev;
drop index ems__incidents_crashes_crash_pk_index;
drop index ems__incidents_crashes_incident_received_datetime_index;
drop index ems__incidents_apd_incident_numbers_index;
drop index ems__incidents_geometry_index;
drop index crashes_case_id_index on crashes (case_id);
drop index idx_ems_geometry_geography;
drop index idx_crashes_position_geography;
drop function update_crash_ems_match();
