insert into lookups.agency (id, label, source) values (10149, 'TEXAS A&M FOREST SERVICE', 'cris');
insert into lookups.agency (id, label, source) values (10236, 'CITY OF BURLESON', 'cris');
insert into lookups.agency (id, label, source) values (3379, 'CALDWELL COUNTY CONSTABLE OFFICE PCT. 4', 'cris');
insert into lookups.agency (id, label, source) values (3380, 'MIDWAY ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3381, 'MOODY ISD POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3382, 'SCURRY POLICE DEPARTMENT', 'cris');
insert into lookups.agency (id, label, source) values (3383, 'JACK COUNTY SHERIFF''S OFFICE', 'cris');
insert into lookups.veh_make (id, label, source) values (820, 'KUBOTA', 'cris');
insert into lookups.veh_make (id, label, source) values (821, 'BOBCAT', 'cris');
insert into lookups.veh_make (id, label, source) values (822, 'BUGATTI RIMAC', 'cris');
insert into lookups.veh_make (id, label, source) values (823, 'CF MOTO', 'cris');
insert into lookups.veh_make (id, label, source) values (824, 'EVOBUS GMBH', 'cris');
insert into lookups.veh_make (id, label, source) values (825, 'INEOS AUTOMOTIVE LIMITED', 'cris');
insert into lookups.veh_make (id, label, source) values (826, 'NIKOLA', 'cris');
insert into lookups.veh_make (id, label, source) values (827, 'RIZON ELECTRIC', 'cris');
insert into lookups.veh_make (id, label, source) values (828, 'TERMINAL INVESTMENT CORP', 'cris');
insert into lookups.veh_mod (id, label, source) values (5970, 'UNKNOWN', 'cris');
insert into lookups.veh_mod (id, label, source) values (5971, 'T770', 'cris');
insert into lookups.veh_mod (id, label, source) values (5972, 'UNKNOWN', 'cris');
insert into lookups.veh_mod (id, label, source) values (5973, 'CYBERTRUCK', 'cris');
insert into lookups.veh_mod (id, label, source) values (5974, 'ADX', 'cris');
insert into lookups.veh_mod (id, label, source) values (5975, 'VALOUR', 'cris');
insert into lookups.veh_mod (id, label, source) values (5976, 'Q6 E-TRON', 'cris');
insert into lookups.veh_mod (id, label, source) values (5977, 'S E-TRON GT', 'cris');
insert into lookups.veh_mod (id, label, source) values (5978, 'SQ6 E-TRON', 'cris');
insert into lookups.veh_mod (id, label, source) values (5979, 'I5', 'cris');
insert into lookups.veh_mod (id, label, source) values (5980, 'R 12', 'cris');
insert into lookups.veh_mod (id, label, source) values (5981, 'NEVERA', 'cris');
insert into lookups.veh_mod (id, label, source) values (5982, 'ENVISTA', 'cris');
insert into lookups.veh_mod (id, label, source) values (5983, '8TT', 'cris');
insert into lookups.veh_mod (id, label, source) values (5984, '8Y', 'cris');
insert into lookups.veh_mod (id, label, source) values (5985, 'ELECTRIC TRACTOR TRUCK', 'cris');
insert into lookups.veh_mod (id, label, source) values (5986, 'TRANSIT BUS 45FT', 'cris');
insert into lookups.veh_mod (id, label, source) values (5987, 'TYPE-A ELECTRIC SCHOOL BUS', 'cris');
insert into lookups.veh_mod (id, label, source) values (5988, 'TYPE-D ELECTRIC SCHOOL BUS', 'cris');
insert into lookups.veh_mod (id, label, source) values (5989, 'CELESTIQ', 'cris');
insert into lookups.veh_mod (id, label, source) values (5990, 'OPTIQ', 'cris');
insert into lookups.veh_mod (id, label, source) values (5991, 'VISTIQ', 'cris');
insert into lookups.veh_mod (id, label, source) values (5992, 'MAVERICK R', 'cris');
insert into lookups.veh_mod (id, label, source) values (5993, 'MAVERICK R MAX', 'cris');
insert into lookups.veh_mod (id, label, source) values (5994, 'ORIGIN', 'cris');
insert into lookups.veh_mod (id, label, source) values (5995, 'PULSE', 'cris');
insert into lookups.veh_mod (id, label, source) values (5996, '300SS', 'cris');
insert into lookups.veh_mod (id, label, source) values (5997, '700 CL-X', 'cris');
insert into lookups.veh_mod (id, label, source) values (5998, '5500HG', 'cris');
insert into lookups.veh_mod (id, label, source) values (5999, '5500XG', 'cris');
insert into lookups.veh_mod (id, label, source) values (6000, 'BRIGHTDROP 400', 'cris');
insert into lookups.veh_mod (id, label, source) values (6001, 'BRIGHTDROP 600', 'cris');
insert into lookups.veh_mod (id, label, source) values (6002, 'SUBURBAN HD', 'cris');
insert into lookups.veh_mod (id, label, source) values (6003, 'S40 TOURRIDER BUSINESS', 'cris');
insert into lookups.veh_mod (id, label, source) values (6004, 'S50 TOURRIDER PREMIUM', 'cris');
insert into lookups.veh_mod (id, label, source) values (6005, 'SEVERE SERVICE', 'cris');
insert into lookups.veh_mod (id, label, source) values (6006, '12 CILINDRI SPIDER', 'cris');
insert into lookups.veh_mod (id, label, source) values (6007, 'TERRITORY', 'cris');
insert into lookups.veh_mod (id, label, source) values (6008, 'CASCADIA 126 RA', 'cris');
insert into lookups.veh_mod (id, label, source) values (6009, 'EM2', 'cris');
insert into lookups.veh_mod (id, label, source) values (6010, 'FLHXU', 'cris');
insert into lookups.veh_mod (id, label, source) values (6011, 'FLTRXP', 'cris');
insert into lookups.veh_mod (id, label, source) values (6012, 'FLTRXSTSE', 'cris');
insert into lookups.veh_mod (id, label, source) values (6013, 'FXLRST', 'cris');
insert into lookups.veh_mod (id, label, source) values (6014, 'ZX350', 'cris');
insert into lookups.veh_mod (id, label, source) values (6015, 'HINO L6', 'cris');
insert into lookups.veh_mod (id, label, source) values (6016, 'HINO XL7', 'cris');
insert into lookups.veh_mod (id, label, source) values (6017, 'ADV160', 'cris');
insert into lookups.veh_mod (id, label, source) values (6018, 'PROLOGUE', 'cris');
insert into lookups.veh_mod (id, label, source) values (6019, 'TRX700', 'cris');
insert into lookups.veh_mod (id, label, source) values (6020, '701 ENDURO', 'cris');
insert into lookups.veh_mod (id, label, source) values (6021, 'TC150', 'cris');
insert into lookups.veh_mod (id, label, source) values (6022, 'TC300', 'cris');
insert into lookups.veh_mod (id, label, source) values (6023, 'TE 150', 'cris');
insert into lookups.veh_mod (id, label, source) values (6024, 'IONIQ 9', 'cris');
insert into lookups.veh_mod (id, label, source) values (6025, 'SPORT SCOUT', 'cris');
insert into lookups.veh_mod (id, label, source) values (6026, 'SUPER SCOUT', 'cris');
insert into lookups.veh_mod (id, label, source) values (6027, 'GRENADIER', 'cris');
insert into lookups.veh_mod (id, label, source) values (6028, 'WAGONEER S', 'cris');
insert into lookups.veh_mod (id, label, source) values (6029, 'BJ230', 'cris');
insert into lookups.veh_mod (id, label, source) values (6030, 'ER500', 'cris');
insert into lookups.veh_mod (id, label, source) values (6031, 'KAT1000', 'cris');
insert into lookups.veh_mod (id, label, source) values (6032, 'KVF450', 'cris');
insert into lookups.veh_mod (id, label, source) values (6033, 'KWF1000', 'cris');
insert into lookups.veh_mod (id, label, source) values (6034, 'NR001', 'cris');
insert into lookups.veh_mod (id, label, source) values (6035, 'NX011', 'cris');
insert into lookups.veh_mod (id, label, source) values (6036, 'EV9', 'cris');
insert into lookups.veh_mod (id, label, source) values (6037, 'REVUELTO', 'cris');
insert into lookups.veh_mod (id, label, source) values (6038, 'RZ', 'cris');
insert into lookups.veh_mod (id, label, source) values (6039, 'TX', 'cris');
insert into lookups.veh_mod (id, label, source) values (6040, 'S2AP', 'cris');
insert into lookups.veh_mod (id, label, source) values (6041, 'S2DM', 'cris');
insert into lookups.veh_mod (id, label, source) values (6042, 'S2MH', 'cris');
insert into lookups.veh_mod (id, label, source) values (6043, 'ELETRE', 'cris');
insert into lookups.veh_mod (id, label, source) values (6044, 'EMIRA', 'cris');
insert into lookups.veh_mod (id, label, source) values (6045, 'GRAVITY', 'cris');
insert into lookups.veh_mod (id, label, source) values (6046, 'MV AGUSTA/F3', 'cris');
insert into lookups.veh_mod (id, label, source) values (6047, 'MV AGUSTA/S3', 'cris');
insert into lookups.veh_mod (id, label, source) values (6048, '750S', 'cris');
insert into lookups.veh_mod (id, label, source) values (6049, 'CLE', 'cris');
insert into lookups.veh_mod (id, label, source) values (6050, 'EQE SEDAN', 'cris');
insert into lookups.veh_mod (id, label, source) values (6051, 'EQE SUV', 'cris');
insert into lookups.veh_mod (id, label, source) values (6052, 'EQS SEDAN', 'cris');
insert into lookups.veh_mod (id, label, source) values (6053, 'EQS SUV', 'cris');
insert into lookups.veh_mod (id, label, source) values (6054, 'ESPRINTER', 'cris');
insert into lookups.veh_mod (id, label, source) values (6055, 'COUNTRYMAN', 'cris');
insert into lookups.veh_mod (id, label, source) values (6056, 'D4020 ISTV', 'cris');
insert into lookups.veh_mod (id, label, source) values (6057, 'TRE FCEV', 'cris');
insert into lookups.veh_mod (id, label, source) values (6058, 'KICKS PLAY', 'cris');
insert into lookups.veh_mod (id, label, source) values (6059, '589', 'cris');
insert into lookups.veh_mod (id, label, source) values (6060, '4', 'cris');
insert into lookups.veh_mod (id, label, source) values (6061, 'FEC7KS', 'cris');
insert into lookups.veh_mod (id, label, source) values (6062, 'FEC9KS', 'cris');
insert into lookups.veh_mod (id, label, source) values (6063, 'SPECTRE', 'cris');
insert into lookups.veh_mod (id, label, source) values (6064, 'HIMALAYAN 450', 'cris');
insert into lookups.veh_mod (id, label, source) values (6065, 'PRO-SPOTTER OFF-HWY', 'cris');
insert into lookups.veh_mod (id, label, source) values (6066, 'PRO-SPOTTER ON-HWY', 'cris');
insert into lookups.veh_mod (id, label, source) values (6067, 'CROWN', 'cris');
insert into lookups.veh_mod (id, label, source) values (6068, 'CROWN SIGNIA', 'cris');
insert into lookups.veh_mod (id, label, source) values (6069, 'GRAND HIGHLANDER', 'cris');
insert into lookups.veh_mod (id, label, source) values (6070, 'VF 7', 'cris');
insert into lookups.veh_mod (id, label, source) values (6071, 'ID BUZZ', 'cris');
insert into lookups.veh_mod (id, label, source) values (6072, 'EX90', 'cris');
insert into lookups.veh_mod (id, label, source) values (6073, 'NEW VNL', 'cris');
insert into lookups.veh_mod (id, label, source) values (6074, 'MTN320', 'cris');
insert into lookups.veh_mod (id, label, source) values (6075, 'YFM01', 'cris');
insert into lookups.veh_mod (id, label, source) values (6076, 'YFZ320', 'cris');
insert into lookups.veh_mod (id, label, source) values (6077, 'YZF890', 'cris');
insert into lookups.veh_mod (id, label, source) values (6097, 'B2', 'cris');
update lookups.agency set label = 'EAST TEXAS A&M UNIVERSITY POLICE DEPARTMENT' where id = 2235;
