
insert into lookups.agency (id, label, source) values 
    (23794, 'ANGELINA COLLEGE POLICE DEPARTMENT', 'cris'),
    (23673, 'BURLINGTON NORTHERN SANTA FE RAILROAD COMPANY POLICE DEPARTMENT', 'cris'),
    (23816, 'COLEMAN COUNTY SHERIFF’S OFFICE', 'cris'),
    (23682, 'COMAL COUNTY CONSTABLE’S OFFICE PCT 4', 'cris'),
    (23845, 'COPPER CANYON POLICE DEPARTMENT', 'cris'),
    (23854, 'JEFFERSON COUNTY SHERIFF’S OFFICE', 'cris'),
    (23897, 'SWISHER COUNTY SHERIFF’S OFFICE', 'cris'),
    (23773, 'TRAVIS COUNTY - AUSTIN EMS', 'cris'),
    (23846, 'WILSON COUNTY CONSTABLE OFFICE PRECINCT 3', 'cris'),
    (24043, 'AUSTIN COMMUNITY COLLEGE DISTRICT POLICE DEPARTMENT', 'cris');
