services:
  api:
    build:
      context: .
    ports:
      - "8085:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/usr/src/app
    command: flask run --host=0.0.0.0 --port=5000 --debug
    restart: unless-stopped
